const Banks = [
    'Abu Dhabi Commercial Bank Ltd.',
    'Airtel Payments Bank Ltd',
    'American Express Banking Corp.',
    'Andhra Pradesh Grameena Vikas Bank',
    'Andhra Pragathi Grameena Bank',
    'Arunachal Pradesh Rural Bank',
    'Aryavart Bank',
    'Assam Gramin Vikash Bank',
    'Au Small Finance Bank Ltd.',
    'Australia and New Zealand Banking Group Ltd.',
    'Axis Bank Ltd.',
    'Bandhan Bank Ltd.',
    'Bangiya Gramin Vikash Bank',
    'Bank of America',
    'Bank of Bahrain & Kuwait BSC',
    'Bank of Baroda',
    'Bank of Ceylon',
    'Bank of India',
    'Bank of Maharashtra',
    'Bank of Nova Scotia',
    'Barclays Bank Plc.',
    'Baroda Gujarat Gramin Bank',
    'Baroda Rajasthan Kshetriya Gramin Bank',
    'Baroda UP Bank',
    'BNP Paribas',
    'Canara Bank',
    'Capital Small Finance Bank Ltd',
    'Central Bank of India',
    'Chaitanya Godavari GB',
    'Chhattisgarh Rajya Gramin Bank',
    'Citibank N.A.',
    'City Union Bank Ltd.',
    'Coastal Local Area Bank Ltd',
    'Cooperatieve Rabobank U.A.',
    'Credit Agricole Corporate & Investment Bank',
    'Credit Suisse A.G',
    'CSB Bank Limited',
    'CTBC Bank Co., Ltd.',
    'Dakshin Bihar Gramin Bank',
    'DBS Bank Ltd.',
    'DCB Bank Ltd.',
    'Deutsche Bank',
    'Dhanlaxmi Bank Ltd.',
    'Doha Bank',
    'Ellaquai Dehati Bank',
    'Emirates NBD Bank PJSC',
    'Equitas Small Finance Bank Ltd',
    'ESAF Small Finance Bank Ltd.',
    'Export-Import Bank of India',
    'Federal Bank Ltd.',
    'Fincare Small Finance Bank Ltd.',
    'FINO Payments Bank Ltd',
    'First Abu Dhabi Bank PJSC',
    'FirstRand Bank Ltd.',
    'HDFC',
    'Himachal Pradesh Gramin Bank',
    'HSBC Ltd',
    'ICICI Bank Ltd.',
    'IDBI Bank Limited',
    'IDFC FIRST Bank Limited',
    'India Post Payments Bank Ltd',
    'Indian Bank',
    'Indian Overseas Bank',
    'IndusInd Bank Ltd',
    'Industrial & Commercial Bank of China Ltd.',
    'Industrial Bank of Korea',
    'J.P. Morgan Chase Bank N.A.',
    'J&K Grameen Bank',
    'Jammu & Kashmir Bank Ltd.',
    'Jana Small Finance Bank Ltd',
    'Jharkhand Rajya Gramin Bank',
    'Jio Payments Bank Ltd',
    'JSC VTB Bank',
    'Karnataka Bank Ltd.',
    'Karnataka Gramin Bank',
    'Karnataka Vikas Gramin Bank',
    'Karur Vysya Bank Ltd.',
    'KEB Hana Bank',
    'Kerala Gramin Bank',
    'Kotak Mahindra Bank Ltd',
    'Krishna Bhima Samruddhi LAB Ltd',
    'Krung Thai Bank Public Co. Ltd.',
    'Lakshmi Vilas Bank Ltd.',
    'Madhya Pradesh Gramin Bank',
    'Madhyanchal Gramin Bank',
    'Maharashtra Gramin Bank',
    'Manipur Rural Bank',
    'Mashreq Bank PSC',
    'Meghalaya Rural Bank',
    'Mizoram Rural Bank',
    'Mizuho Bank Ltd.',
    'MUFG Bank, Ltd.',
    'Nagaland Rural Bank',
    'Nainital bank Ltd.',
    'National Australia Bank',
    'National Bank for Agriculture and Rural Development',
    'National Housing Bank',
    'North East Small finance Bank Ltd',
    'NSDL Payments Bank Limited',
    'Odisha Gramya Bank',
    'Paschim Banga Gramin Bank',
    'Paytm Payments Bank Ltd',
    'Prathama U.P. Gramin Bank',
    'PT Bank Maybank Indonesia TBK',
    'Puduvai Bharathiar Grama Bank',
    'Punjab & Sind Bank',
    'Punjab Gramin Bank',
    'Punjab National Bank',
    'Qatar National Bank SAQ',
    'Rajasthan Marudhara Gramin Bank',
    'RBL Bank Ltd.',
    'Saptagiri Grameena Bank',
    'Sarva Haryana Gramin Bank',
    'Saurashtra Gramin Bank',
    'Sberbank',
    'SBI',
    'Shinhan Bank',
    'Shivalik Small Finance Bank Ltd',
    'Small Industries Development Bank of India',
    'Societe Generale',
    'Sonali Bank Ltd.',
    'South Indian Bank Ltd.',
    'Standard Chartered Bank',
    'State Bank of India',
    'Subhadra Local Bank Ltd',
    'Sumitomo Mitsui Banking Corporation',
    'Suryoday Small Finance Bank Ltd.',
    'Tamil Nadu Grama Bank',
    'Tamilnad Mercantile Bank Ltd.',
    'Telangana Grameena Bank',
    'The Royal Bank of Scotland plc',
    'Tripura Gramin Bank',
    'UCO Bank',
    'Ujjivan Small Finance Bank Ltd.',
    'Union Bank of India',
    'United Overseas Bank Ltd.',
    'Utkal Grameen Bank',
    'Utkarsh Small Finance Bank Ltd.',
    'Uttar Bihar Gramin Bank',
    'Uttarakhand Gramin Bank',
    'Uttarbanga Kshetriya Gramin Bank',
    'Vidharbha Konkan Gramin Bank',
    'Westpac Banking Corporation',
    'Woori Bank',
    'YES Bank Ltd.'
];
export default Banks;
