const Department = [
    'Sales',
    'Depot',
    'Engineering',
    'Marketing',
    'Finance',
    'Human Resources',
    'Production',
    'Development',
    'Quality Management',
    'Research',
    'Customer Service',
    'Administration',
    'Purchasing',
    'Shipping',
    'IT',
    'Public Relations',
    'Executive',
    'Accounting',
    'Taxes',
    'Wage accounts',
    'Financial accounts',
    'Cost accounts',
    'Audit',
    'Budgeting',
    'Financial planning',
    'Credit collection',
    'Cash'
];
export default Department;
