const Designation = [
    '.NET Developer',
    'ACCESSIBILITY SPECIALIST',
    'Accounting Manager',
    'Admin Big Data',
    'Administration Assistant',
    'AGILE PROJECT MANAGER',
    'Android Developer',
    'Ansible Automation Engineer',
    'Ansible Operations Engineer',
    'AppDynamics Engineer',
    'Application Security Engineer',
    'Artifactory Administrator',
    'Artifactory Engineer',
    'Artificial Intelligence (AI) / Machine Learning Engineer',
    'Artificial intelligence / Machine Learning Engineer',
    'Artificial Intelligence / Machine Learning Leader',
    'Artificial Intelligence / Machine Learning Sr.Leader',
    'Artificial intelligence Architect',
    'Artificial Intelligence Researcher',
    'Assignment Coordinator',
    'Assistant Engineer',
    'Associate Product Manager',
    'AWS DevOps Engineer',
    'AWS Solutions Architect',
    'Azure DevOps Engineer',
    'Bamboo Engineer',
    'Big Data Architect',
    'Big Data Engineer',
    'Big Data Specialist',
    'Bitbucket Engineer',
    'Blockchain Developer',
    'Build and Release Engineer',
    'Build Engineer',
    'Business Account Manager',
    'Business Development Manager',
    'BUSINESS SYSTEMS ANALYST',
    'C# Developer',
    'Career Advisor',
    'Career Consultant',
    'Career Development Strategist',
    'CEO',
    'Chef InSpec Engineer',
    'Chef Operations Engineer',
    'Chief Architect',
    'Chief Executive Officer',
    'Chief Financial Officer',
    'Chief Human Resource Officer',
    'CIO/Chief Digital Officer/Chief Innovation Officer',
    'Cloud administrator',
    'CLOUD ARCHITECT',
    'Cloud architect',
    'Cloud automation engineer',
    'Cloud engineer',
    'Cloud network engineer',
    'Cloud Security Engineer',
    'CNC Programmer',
    'Coder',
    'COMPUTER GRAPHICS ANIMATOR',
    'Computer Hardware Engineer',
    'Computer Network Architect',
    'Computer Programmer',
    'Computer Research Scientist',
    'Computer Systems Analyst',
    'Confluence Engineer',
    'Consul Engineer',
    'CONTENT MANAGER',
    'CONTENT STRATEGIST',
    'Coverage.py Engineer',
    'CTO',
    'DATA ANALYST',
    'Data Analyst',
    'Data Analysts',
    'Data Architect',
    'DATA ARCHITECT',
    'Data Engineer',
    'DATA MODELER',
    'DATA SCIENTIST',
    'Data Scientist',
    'DATABASE ADMINISTRATOR',
    'Database Administrator',
    'Datadog Engineer',
    'Developer',
    'DevOps Architect',
    'DevOps Engineer',
    'DEVOPS MANAGER',
    'DevSecOps Architect',
    'DevSecOps Engineer',
    'Digital Marketing Analyst',
    'Digital Marketing Manager',
    'DIGITAL MARKETING MANAGER',
    'Director',
    'Director of Engineering',
    'Docker Engineer',
    'ELK Engineer',
    'Embedded Software Engineer',
    'Engineer',
    'Engineering Manager',
    'Engineering Project Manager',
    'Engineering Project Manager/Engineering Manager',
    'Entry Level Developer',
    'Entry Level Network Engineer',
    'Entry Level Programmer',
    'Entry Level Software Developer',
    'Entry Level Software Engineer',
    'Entry Level Web Developer',
    'Envoy Engineer',
    'Falco Engineer',
    'Finance Manager',
    'FluentD Engineer',
    'Fortify Engineer',
    'FRAMEWORKS SPECIALIST',
    'Front End Developer',
    'Front End Web Developer',
    'Front Office Executive',
    'FRONT-END DESIGNER',
    'FRONT-END DEVELOPER',
    'Full Stack Developer',
    'Full Stack JAVA Developer/Programmer/Engineer',
    'Full Stack Python Developer/Programmer/Engineer',
    'FULL-STACK DEVELOPER',
    'Game Developer',
    'GAME DEVELOPER',
    'GCP DevOps Engineer',
    'Gerrit Administrator',
    'Git Engineer',
    'Github Engineer',
    'GitLab Engineer',
    'Grafana Engineer',
    'Groovy Engineer',
    'GROWTH HACKER',
    'HR Business Partner',
    'HR Coordinator',
    'HR Director',
    'HR Generalist',
    'HR Manager',
    'HR Specialist',
    'Human Resource Information Specialist',
    'Human Resources Officer',
    'Human Resources Representative',
    'INFORMATION ARCHITECT',
    'Information Security Analyst',
    'INTERACTION DESIGNER',
    'Intern Software Developer',
    'IOS Developer',
    'Istio Engineer',
    'IT Administrator',
    'IT Infra Manager',
    'IT Manager',
    'Java Developer',
    'JavaScript Developer',
    'Jenkins Engineer',
    'Jira Administrator',
    'JIRA Engineer',
    'Jr Developer',
    'Junior Developer',
    'Junior Front End Developer',
    'Junior IOS Developer',
    'Junior Software Developer',
    'Junior Software Engineer',
    'Junior Web Developer',
    'JUnit Engineer',
    'kubernetes Administrator',
    'Kubernetes Engineer',
    'Kubernetes Operations Engineer',
    'Learning and Development co-ordinators',
    'Learning and Development Manager',
    'Machine learning Architect',
    'Machine Learning Engineer',
    'Marketing Manager',
    'MARKETING TECHNOLOGIST',
    'MAVEN Engineer',
    'Micro services / API Lead Designer',
    'MOBILE APP DEVELOPER',
    'Mobile Application Developer',
    'MOBILE DEVELOPER',
    'Mulesoft Developer',
    'Nagios Engineer',
    'Network and Systems Administrator',
    'Network Engineer',
    'New Grad Software Engineer',
    'Octopus Deploy Engineer',
    'OpenShift Engineer',
    'OpenStack Engineer',
    'Operations Engineer',
    'Oracle Developer',
    'Oracle SQL Developer',
    'Packer Engineer',
    'Payroll Coordinator',
    'Personnel Agent',
    'PHP Developer',
    'Placement Coordinator',
    'Powershell Engineer',
    'Principal Software Engineer',
    'Principle Engineer in Artificial Intelligence',
    'Principle Engineer in Big Data',
    'Principle Engineer in Data Analysis',
    'Principle Engineer in Machine Learning',
    'Procurement manager',
    'Product Manager',
    'PRODUCT MANAGER',
    'Production Support Engineer',
    'Programmer',
    'Programmer Analyst',
    'Project Manager',
    'Prometheus Engineer',
    'Public Accountant',
    'Public Relations Representative',
    'Puppet Engineer',
    'Puppet Operations Engineer',
    'Purchasing Clerk',
    'Purchasing Manager',
    'PyTest Engineer',
    'Python Developer',
    'PYTHON DEVELOPER',
    'QA (QUALITY ASSURANCE) SPECIALIST',
    'QA Engineer',
    'React Developer',
    'Recruiter',
    'Recruiting Coordinator',
    'Recruiting Director',
    'Recruiting Manager',
    'Robotics Engineer',
    'RUBY ON RAILS DEVELOPER',
    'Sales Manager',
    'Sales Representative',
    'Salesforce Developer',
    'Search Engine Optimization',
    'SECURITY SPECIALIST',
    'Selenium Engineer',
    'Senior Ansible Development Engineer',
    'Senior Build and Release Engineer',
    'Senior Build Engineer',
    'Senior Cloud Architect',
    'Senior DevOps Architect',
    'Senior DevOps Engineer',
    'Senior DevSecOps Architect',
    'Senior DevSecOps Engineer',
    'Senior Director',
    'Senior Engineer',
    'Senior Manager IT',
    'Senior Product Manager',
    'Senior Project Manager',
    'Senior Site reliability Engineer',
    'Senior Software Engineer/Senior Software Developer',
    'Senior SRE Architect',
    'Senior SRE Engineer',
    'Senior Technical Lead',
    'Senior Vice President',
    'SEO CONSULTANT',
    'SEO Engineer',
    'SEO Manager',
    'Sharepoint Developer',
    'Shipping Clerk',
    'Site Reliability Engineer (Kubernetes – Docker)',
    'SOCIAL MEDIA MANAGER',
    'Social Media Marketing Analyst',
    'Social Media Marketing Manager',
    'Software Architect',
    'Software Developer',
    'SOFTWARE DEVELOPERS',
    'Software Engineer',
    'SonarQube Engineer',
    'Splunk Engineer',
    'Splunk Enterprise Security Engineer',
    'SQL Developer',
    'SRE Architect',
    'SRE Engineer',
    'Staff',
    'Stock Clerk',
    'Stock Manager',
    'SYSTEMS ADMINISTRATOR',
    'SYSTEMS ENGINEER',
    'TeamCity Engineer',
    'Tech Sales Engineer',
    'TECHNICAL ACCOUNT MANAGER',
    'TECHNICAL LEAD',
    'Technical Lead/Engineering Lead/Team Lead',
    'Technical Project Manager',
    'Technique Leader',
    'Terraform Engineer',
    'TFS Engineer',
    'Twistkock Engineer',
    'UDeploy Engineer',
    'UI DESIGNER',
    'UI Developer',
    'Unity Developer',
    'UX DESIGNER',
    'Vault Engineer',
    'VP',
    'VP of Engineering',
    'VP of Engineering/Director of Engineering',
    'VP of HR',
    'VP of Product Management/Head of Product',
    'WEB ANALYTICS DEVELOPER',
    'Web Designer (UI/UX Designer)',
    'Web Developer',
    'WordPress Developer',
    'WORDPRESS DEVELOPER'
];
export default Designation;
