const Districts = {
    'Andaman & Nicobar Islands *': ['Andamans'],
    'Andhra Pradesh': [
        'Adilabad',
        'Kurnool',
        'Chittoor',
        'Cuddapah',
        'Rangareddi',
        'Srikakulam',
        'East Godavari',
        'Visakhapatnam',
        'Anantapur',
        'Mahbubnagar',
        'Guntur',
        'Prakasam',
        'Khammam',
        'West Godavari',
        'Nalgonda',
        'Vizianagaram',
        'Nizamabad',
        'Medak',
        'Krishna',
        'Nellore',
        'Hyderabad and Rangareddi',
        'Karimnagar',
        'Warangal',
        'Hyderabad'
    ],
    'Arunachal Pradesh': [
        'West Siang',
        'West Kameng',
        'Changlang',
        'Upper Subansiri',
        'Tirap',
        'Papum Pare',
        'Lohit',
        'East Siang',
        'Dibang Valley',
        'East Kameng',
        'Tawang',
        'Lower Subansiri'
    ],
    Assam: [
        'Bongaigaon',
        'Cachar',
        'Sibsagar',
        'Dhubri',
        'Karimganj',
        'Tinsukia',
        'Kamrup',
        'Dibrugarh',
        'Golaghat',
        'Barpeta',
        'Kokrajhar',
        'Lakhimpur',
        'Sonitpur',
        'Karbi Anglong',
        'Jorhat',
        'Nagaon',
        'Dhemaji',
        'Goalpara',
        'North Cachar Hills',
        'Hailakandi',
        'Marigaon',
        'Darrang',
        'Nalbari'
    ],
    Bihar: [
        'Banka',
        'Araria',
        'Purba Champaran',
        'Bhojpur',
        'Munger',
        'Aurangabad',
        'Pashchim Champaran',
        'Kishanganj',
        'Sitamarhi',
        'Patna',
        'Purnia',
        'Lakhisarai',
        'Gopalganj',
        'Begusarai',
        'Sheikhpura',
        'Kaimur (Bhabua)',
        'Bhagalpur',
        'Nalanda',
        'Rohtas',
        'Supaul',
        'Gaya',
        'Buxar',
        'Saran',
        'Samastipur',
        'Darbhanga',
        'Madhubani',
        'Khagaria',
        'Vaishali',
        'Nawada',
        'Jamui',
        'Jehanabad',
        'Muzaffarpur',
        'Katihar',
        'Madhepura',
        'Siwan',
        'Saharsa',
        'Sheohar'
    ],
    'Chandigarh *': ['Chandigarh'],
    Chhattisgarh: [
        'Durg',
        'Janjgir-Champa',
        'Rajnandgaon',
        'Surguja',
        'Raipur',
        'Dantewada',
        'Mahasamund',
        'Koriya',
        'Bilaspur',
        'Dhamtari',
        'Raigarh',
        'Korba',
        'Bastar',
        'Jashpur',
        'Kanker',
        'Kawardha'
    ],
    'Dadra & Nagar Haveli *': ['Dadra & Nagar Haveli'],
    'Daman & Diu *': ['Daman', 'Diu'],
    'Delhi *': [
        'North West',
        'South',
        'North East',
        'North',
        'South West',
        'East',
        'In all 9 dsitricts',
        'West',
        'New Delhi, Central, South West and South'
    ],
    Goa: ['North Goa', 'South Goa'],
    Gujarat: [
        'Porbandar',
        'Mahesana',
        'Navsari',
        'Jamnagar',
        'Valsad',
        'Gandhinagar',
        'Ahmadabad',
        'Bhavnagar',
        'Banas Kantha',
        'Amreli',
        'Anand',
        'Bharuch',
        'Kachchh',
        'Vadodara',
        'Kheda',
        'Junagadh',
        'Surat',
        'Rajkot',
        'Patan',
        'Dohad',
        'Surendranagar',
        'Panch Mahals',
        'Sabar Kantha',
        'Narmada'
    ],
    Haryana: [
        'Ambala',
        'Panipat',
        'Karnal',
        'Mahendragarh',
        'Jhajjar',
        'Hisar',
        'Rewari',
        'Bhiwani',
        'Yamunanagar',
        'Kaithal',
        'Gurgaon',
        'Sirsa',
        'Faridabad',
        'Fatehabad',
        'Sonipat',
        'Jind',
        'Rohtak',
        'Panchkula',
        'Kurukshetra'
    ],
    'Himachal Pradesh': ['Solan', 'Chamba', 'Kullu', 'Hamirpur', 'Bilaspur', 'Shimla', 'Una', 'Kangra', 'Mandi', 'Sirmaur'],
    'Jammu and Kashmir': [
        'Anantnag',
        'Jammu',
        'Pulwama',
        'Srinagar',
        'Badgam',
        'Baramula',
        'Doda',
        'Kathua',
        'Udhampur',
        'Kupwara',
        'Kargil',
        'Leh (Ladakh)',
        'Rajauri',
        'Punch'
    ],
    Jharkhand: [
        'Pashchimi Singhbhum',
        'Bokaro',
        'Dhanbad',
        'Hazaribag',
        'Purbi Singhbhum',
        'Palamu',
        'Dumka',
        'Ranchi',
        'Chatra',
        'Deoghar',
        'Giridih',
        'Garhwa',
        'Godda',
        'Lohardaga',
        'Kodarma',
        'Pakaur',
        'Sahibganj',
        'Gumla'
    ],
    Karnataka: [
        'Tumkur',
        'Dakshina Kannada',
        'Gulbarga',
        'Dharwad',
        'Hassan',
        'Uttara Kannada',
        'Bangalore',
        'Belgaum',
        'Bidar',
        'Bagalkot',
        'Kolar',
        'Haveri',
        'Mysore',
        'Bijapur',
        'Bellary',
        'Shimoga',
        'Chikmagalur',
        'Chitradurga',
        'Chamarajanagar',
        'Davanagere',
        'Bangalore Rural',
        'Raichur',
        'Gadag',
        'Koppal',
        'Kodagu',
        'Udupi',
        'Mandya'
    ],
    Kerala: [
        'Pathanamthitta',
        'Thrissur',
        'Alappuzha',
        'Ernakulam',
        'Kannur',
        'Thiruvananthapuram',
        'Kasaragod',
        'Kozhikode',
        'Kottayam',
        'Palakkad',
        'Idukki',
        'Wayanad',
        'Kollam',
        'Malappuram'
    ],
    'Lakshadweep *': ['Lakshadweep'],
    'Madhya Pradesh': [
        'Shajapur',
        'Panna',
        'Bhind',
        'Jhabua',
        'Ratlam',
        'Shahdol',
        'Satna',
        'Chhindwara',
        'Morena',
        'Betul',
        'Barwani',
        'Gwalior',
        'Guna',
        'Sehore',
        'Hoshangabad',
        'Chhatarpur',
        'Tikamgarh',
        'Shivpuri',
        'Raisen',
        'Ujjain',
        'Dhar',
        'Sheopur',
        'Dewas',
        'Balaghat',
        'Rewa',
        'Mandla',
        'Sagar',
        'Damoh',
        'Jabalpur',
        'Seoni',
        'Katni',
        'West Nimar',
        'Vidisha',
        'Bhopal',
        'Indore',
        'Datia',
        'Mandsaur',
        'Rajgarh',
        'East Nimar',
        'Umaria',
        'Narsimhapur',
        'Sidhi',
        'Neemuch',
        'Dindori',
        'Harda'
    ],
    Maharashtra: [
        'Amravati',
        'Ahmadnagar',
        'Latur',
        'Kolhapur',
        'Solapur',
        'Akola',
        'Pune',
        'Raigarh',
        'Jalgaon',
        'Jalna',
        'Thane',
        'Bid',
        'Wardha',
        'Sangli',
        'Aurangabad',
        'Hingoli',
        'Chandrapur',
        'Nashik',
        'Bhandara',
        'Osmanabad',
        'Nanded',
        'Buldana',
        'Nagpur',
        'Ratnagiri',
        'Yavatmal',
        'Gadchiroli',
        'Dhule',
        'Parbhani',
        'Satara',
        'Gondiya',
        'Mumbai (Suburban) and Mumbai',
        'Sindhudurg',
        'Washim',
        'Nandurbar'
    ],
    Manipur: [
        'Imphal East',
        'Bishnupur',
        'Thoubal',
        'Imphal West & Imphal East',
        'Imphal West',
        'Thoubal & Imphal West',
        'Chandel',
        'Bishnupur & Imphal West'
    ],
    Meghalaya: [
        'South Garo Hills',
        'East Khasi Hills',
        'Jaintia Hills',
        'West Khasi Hills',
        'Ri Bhoi',
        'East Garo Hills',
        'West Garo Hills'
    ],
    Mizoram: ['Aizawl', 'Kolasib', 'Serchhip', 'Champhai', 'Lunglei', 'Mamit', 'Saiha'],
    Nagaland: ['Dimapur', 'Kohima', 'Mokokchung', 'Mon', 'Phek', 'Tuensang', 'Wokha', 'Zunheboto'],
    Orissa: [
        'Kendujhar',
        'Anugul',
        'Ganjam',
        'Cuttack',
        'Balangir',
        'Baleshwar',
        'Malkangiri',
        'Khordha',
        'Bargarh',
        'Mayurbhanj',
        'Bhadrak',
        'Baudh',
        'Jharsuguda',
        'Kalahandi',
        'Dhenkanal',
        'Sonapur',
        'Sundargarh',
        'Rayagada',
        'Sambalpur',
        'Jajapur',
        'Nayagarh',
        'Koraput',
        'Debagarh',
        'Kandhamal',
        'Jagatsinghapur',
        'Gajapati',
        'Kendrapara',
        'Nuapada',
        'Nabarangapur',
        'Puri'
    ],
    'Pondicherry *': ['Karaikal', 'Pondicherry', 'Mahe', 'Yanam'],
    Punjab: [
        'Firozpur',
        'Jalandhar',
        'Sangrur',
        'Amritsar',
        'Ludhiana',
        'Fatehgarh Sahib',
        'Rupnagar',
        'Moga',
        'Nawanshahr',
        'Patiala',
        'Mansa',
        'Muktsar',
        'Gurdaspur',
        'Bathinda',
        'Kapurthala',
        'Hoshiarpur',
        'Faridkot'
    ],
    Rajasthan: [
        'Ganganagar',
        'Sirohi',
        'Ajmer',
        'Jhalawar',
        'Alwar',
        'Rajsamand',
        'Baran',
        'Bhilwara',
        'Jhunjhunun',
        'Jaipur',
        'Pali',
        'Barmer',
        'Dausa',
        'Banswara',
        'Dhaulpur',
        'Chittaurgarh',
        'Nagaur',
        'Bharatpur',
        'Saharanpur',
        'Hanumangarh',
        'Udaipur',
        'Jalor',
        'Churu',
        'Bikaner',
        'Jodhpur',
        'Bundi',
        'Kota',
        'Tonk',
        'Dungarpur',
        'Sikar',
        'Sawai Madhopur',
        'Karauli',
        'Jaisalmer'
    ],
    Sikkim: ['East', 'West', 'South', 'North'],
    'Tamil Nadu': [
        'Coimbatore',
        'Madurai',
        'Ramanathapuram',
        'Tirunelveli',
        'Kancheepuram',
        'Kanniyakumari',
        'The Nilgiris',
        'Thanjavur',
        'Dindigul',
        'Namakkal',
        'Vellore',
        'Pudukkottai',
        'Virudhunagar',
        'Toothukudi',
        'Thiruvallur',
        'Erode',
        'Viluppuram',
        'Theni',
        'Cuddalore',
        'Tiruvanamalai',
        'Salem',
        'Kapur',
        'Ariyalur',
        'Perambalur',
        'Dharmapuri',
        'Tiruchirappalli',
        'Chennai',
        'Sivaganga',
        'Nagapattinam',
        'Thiruvarur'
    ],
    Tripura: ['West Tripura', 'South Tripura', 'Dhalai', 'North Tripura'],
    'Uttar Pradesh': [
        'Auraiya',
        'Agra',
        'Mau',
        'Bijnor',
        'Baghpat',
        'Mirzapur',
        'Muzaffarnagar',
        'Gorakhpur',
        'Kaushambi',
        'Kanpur Dehat',
        'Ambedaker Nagar',
        'Etah',
        'Aligarh',
        'Allahabad',
        'Shahjahanpur',
        'Budaun',
        'Saharanpur',
        'Lucknow',
        'Sultanpur',
        'Azamgarh',
        'Meerut',
        'Jyotiba Phule Nagar',
        'Maharajganj',
        'Sonbhadra',
        'Pratapgarh',
        'Bulandshahr',
        'Bareilly',
        'Kanpur Nagar',
        'Banda',
        'Mathura',
        'Unnao',
        'Faizabad',
        'Jhansi',
        'Ghaziabad',
        'Rae Bareli',
        'Ghazipur',
        'Moradabad',
        'Bahraich',
        'Fatehpur',
        'Etawah',
        'Ballia',
        'Balrampur',
        'Barabanki',
        'Siddharthnagar',
        'Varanasi',
        'Pilibhit',
        'Kheri',
        'Basti',
        'Hardoi',
        'Mainpuri',
        'Sant Ravidas Nagar',
        'Deoria',
        'Shrawasti',
        'Rampur',
        'Gautam Buddha Nagar',
        'Sitapur',
        'Chandauli',
        'Mahoba',
        'Kannauj',
        'Chitrakoot',
        'Gonda',
        'Jaunpur',
        'Firozabad',
        'Farrukhabad',
        'Hamirpur',
        'Sant Kabir Nagar',
        'Hathras',
        'Kushinagar',
        'Jalaun',
        'Lalitpur'
    ],
    Uttaranchal: [
        'Almora',
        'Chamoli',
        'Bageshwar',
        'Udham Singh Nagar',
        'Champawat',
        'Uttarkashi',
        'Hardwar',
        'Nainital',
        'Dehradun',
        'Tehri Garhwal',
        'Tehri Garhwal & Garhwal',
        'Pithoragarh',
        'Garhwal',
        'Rudraprayag'
    ],
    'West Bengal': [
        'Puruliya',
        'Birbhum',
        'Maldah',
        'Nadia',
        'Jalpaiguri',
        'Haora',
        'Barddhaman',
        'Hugli',
        'South Twentyfour Parganas',
        'Murshidabad',
        'North Twentyfour Parganas',
        'Medinipur',
        'Darjiling',
        'Dakshin Dinajpur',
        'Bankura',
        'Koch Bihar',
        'Uttar Dinajpur',
        'Kolkata',
        'Darjiling and Jalpaiguri'
    ]
};
export default Districts;
