// eslint-disable-next-line import/prefer-default-export
export const ESIHospitals = {
    IMP: {
        Karnataka: {
            Bangalore: ['Prakash'],
            Bidar: ['Dr.VEERENDRA PATIL', 'Dr.Somshekhar Bhalke', 'Dr.Suman Bhalke', 'Dr.suman Bhalke'],
            Chamarajanagar: ['Dr . Basavaraju', 'Dr . Nagarjuna'],
            Chickmagalore: ['Dr.SIDDAIAH K G', 'Dr.Srinivas D'],
            Chickballapura: ['Mr.Dr. Shashidhar Kumar H.S.', 'Dr.K S RATHNAMMA', 'Dr.venkatesh prasad', 'Dr.poornima P V'],
            Chitradurga: ['Dr. S. D. Lokesh'],
            Kalburgi: ['Mr.gouti'],
            Kodagu: ['Mr.Goutham', 'Dr.Mohan K A', 'Dr.Divya Kurambaiah'],
            Shimoga: ['Dr. Gajanan Venkatarman Hegde']
        },
        Telangana: {
            Hyderabad: ['Dr.R.Pratap Naik', 'Mr.Gowtham'],
            Karimnagar: [
                'Dr. M.Rajam',
                'Dr. Anantha Reddy',
                'Dr. U. V. Vishnuvardan Reddy',
                'Dr.Ishfaq ali',
                'Mr.vineeth',
                'Dr.Venkata Vishnuvardhan Reddy U',
                'Dr.Geetha Vani Guduri'
            ],
            Khamman: ['Dr. V. Vijay Kumar', 'Dr.Koteshwar Rao', 'Dr.Srikanth.B'],
            Mahbubnagar: [
                'Dr. N. Livingston',
                'Dr.Vijaya Laxmi Rathod',
                'Dr.G.R. Yugandhar',
                'Dr.P.Shashi Kumar',
                'Dr. K. Dilip Chandra, MS',
                'Dr.Krupakar Reddy, MBBS',
                'Dr.Suganya Rao, MBBS',
                'Dr.K.Lakshmaiah, MBBS',
                'Dr.Venkateswar',
                'Dr.Balram J',
                'Dr.Krishna Jyothi Aluwala',
                'Dr.Natraj',
                'Dr.Srinivasulu A',
                'Dr.Sravanthi B',
                'Dr.Neelophar Jagirdar',
                'Dr.Krupakar Reddy',
                'Dr.Krishna Jyothi'
            ],
            Medak: [
                'Dr.A.Pundarikam, M.B.B.S.',
                'Dr.G.Srihari',
                'Dr. Ramu.K',
                'Dr. Murtuza Ali Khan, MD,',
                'Dr.G.Aparna',
                'Dr.Satish Kumar P',
                'Dr.Gyaneshwer Adepu',
                'Dr.Venkatesham K',
                'Dr.Liyaqath Ali',
                'Dr.Ramu K',
                'Dr.Ramesh Ponugoti',
                'Dr.Srihari G',
                'Dr.Suhasini T',
                'Dr.HEMRAJ SINGH'
            ],
            Nalgoda: [
                'Dr.V.Yadagiri',
                'Dr. B . Basavapunna Rao, M.B.B.S, D.L.O(ENT)',
                'Dr. B. Vijay Kumar, MBBS',
                'Dr. M. Pratap Reddy',
                'Dr.K.Guvaiah, MBBS',
                'Dr. J. Ramachandrudu, MS',
                'Dr.k.Sreepathi Reddy, MBBS',
                'Dr.Suresh Kothapalli',
                'Dr.Ramachandrudu.J',
                'Dr.Pratap Reddy Mekala',
                'Dr.Sripathi Reddy Kakumanu'
            ],
            Nizamabad: [
                'Dr.G.Laxminarayana, MBBS',
                'D.M.V.Ramana',
                'Dr.I.Jayalakshmi,MBBS',
                'Dr.Chandrakala Banothu',
                'Dr.Mothilal Kethavath',
                'Dr.Balveer Singh Nainavath',
                'Dr.Jayalakshmi Innamudi',
                'Dr.Venkataramana Mamidipally',
                'Dr.JAYALAKSHMI INNAMURI'
            ],
            Rangareddy: [
                'Dr. V.SRINIVAS RAO',
                'Dr.G.Satyanarayana Raju',
                'Dr. B. Vankata Subbammma',
                'Dr. Mohd. Jahangir, MBBS',
                'Dr.K.Suresh Reddy',
                'Dr. M. V. Prabhakar , MBBS',
                'Dr.J.Chalapathi Rao',
                'Dr.B.Rajitha',
                'Dr.G.Anil Kumar, MBBS',
                'Bhaktavatsalam',
                'Dr.Shravan Kumar',
                'Dr.Anil Kumar G',
                'Dr.Ramanjaneyulu B',
                'Dr.Mallikarjun V',
                'Mallikarjun V',
                'Dr.Rajini',
                'Dr.N KALYAN MOHAN RAO',
                'NAMAWARAM',
                'Dr.RAMDAS NAIK.R'
            ],
            Siddipet: ['Dr.LINGAM ALISHALA', 'Dr.GURRAM THIRUPATHI', 'Dr.ONTEDDU JOSEPH UDAY KUMAR'],
            Suryapet: ['Dr.BODANAPALLY NIKHIL', 'Dr.GURVAIAH KAMBHAMPATI'],
            Warangal: [
                'Dr. P. Karunakar Raju, MBBS',
                'Dr.K.S.Kiran',
                'Dr.D.Madhusudhan Reddy, MBBS',
                'Dr.Surendra Mohan Srivastava,',
                'Dr.Surenda Mohan Srivasthava',
                'Dr.Bharat Damera',
                'Dr.Vijay Kumar A',
                'Dr.Karunakar Raju P',
                'Dr.Shanthi Kiran Kosaraju'
            ]
        },
        Maharashtra: {
            Ahmednagar: [
                'Dr.Ganesh Ramdas Gavhane',
                'Dr.Shashank',
                'Dr.Satish Sudhakar Trymbake',
                'Dr.Santosh Ankush Pathare',
                'Dr.Mahadev Nagnathappa Randale',
                'Dr.Akash Kiran Somvanshi',
                'Dr.Dhananjay Sampatrao',
                'Dr.Ram Appasaheb magar',
                'Dr.Shrikant Chandrakant pathak',
                'Dr.Govada Sunny Prakash',
                'Dr.Pankaj Pandurang Kshirsagar'
            ],
            Amrawati: ['Mrs.Dr. Jyotsna Sanjay Deshmulh', 'Dr.Dr. Devendra K Agrawal'],
            Aurangabad: ['Vasudha'],
            Beed: ['Dr.Vasudha Rahul jaju'],
            Buldhana: ['Dr. Prakash N. Maloo', 'Dr. Sampada Nimbhorkar'],
            Dhule: ['Mr.NITIN WAMANRAO NIKAM'],
            Gondiya: ['Dr. Prafull Shah'],
            Jalgaon: ['Dr.Dipti Arun Chaudhari'],
            Jalna: [
                'Rajendra',
                'Puja',
                'Aniket',
                'Dr.Nilesh Onkardas Agrawal',
                'Dr.Ritesh Onkardas Agrawal',
                'Dr.Kailash Dargad',
                'Dr.Neeru Ritesh Agrawal',
                'Dr.bagal Sham Pandurang'
            ],
            Kolhapur: [
                'Mr.Dr. Ajay Raghunath Bidkar',
                'Mr.Dr. Jaykuamr Shankarrao Dang',
                'Mr.Dr. Mukund Mahadeo Sadigale',
                'Mr.Dr. Parashram Subarao Patil',
                'Mr.Dr. Prashant Anandrao Gaikwad',
                'Mr.Dr. Rajnish Balaso Shankardas',
                'Mrs.Dr. Rupali Mahesh Dalvi',
                'Mr.Dr. Sadhanarani Rajnish Shanka',
                'Mr.Dr. Satagonda Devagonda Patil',
                'Mr.Dr. Smita Dhanykumar Bhokare',
                'Dr.RAJENDRA BHUPAL DIGRAJE',
                'Dr.Sagar Shivaji Gosavi',
                'Dr.Ajay Raghunath bidkar'
            ],
            Nagpur: [
                'Dr. Rekha Nimje',
                'Dr. Shalvin Nimje',
                'Dr. Jayat V. Deshmukh',
                'Dr. Asim Alim',
                'Dr. Viraj V. Jaiswal',
                'Mr.Dr. Khan Md Arif Khan Abdul Ra',
                'Mrs.Dr. Azmi Rehan Altafur Rahim',
                'Mr.Dr. Kapilkumar Shrinandlal Jai',
                'Dr.Rajesh Madhukar Pawde'
            ],
            Nashik: [
                'Mr.KIRAN RANGNATH KHELUKAR',
                'Shyamkant',
                'Dr.Kalindi Yogesh Patil',
                'Dr.sayyad Nikhat Anjum Hamid',
                'Dr.Naikwadi Aman mubarak'
            ],
            Osmanabad: ['Vadgaonkar', 'Dr.Sujit Arunrao Magar', 'Dr.Vishal Ramesh Vadgaonkar'],
            Palghar: [
                'Dr.Dr. Anil Ashok Kamath',
                'Dr.Dr. Ashok Baliram Bharane',
                'Dr.Dr. Dinesh Chand Goyal',
                'Dr.Dr. Geeta Suryanarayan Raju Gu',
                'Dr.Dr. Gopal Prakash Ghuge',
                'Dr.Dr. Kalpana Vitthal Barapatre',
                'Dr.Dr. Sandip Jotiram Latke',
                'Dr.Dr. Utkarsh Anilkumar Singh',
                'Mrs.UJJWALA VAIBHAV THAKARE',
                'Mr.Prakash Babu',
                'Mala',
                'Jatin',
                'Kunal',
                'Nita',
                'Chetan',
                'Suchita',
                'Hemchandra',
                'Dr.Yogita Prashant Bhadange',
                'Dr.Siddik Nathu Komg'
            ],
            Raigad: [
                'VD. LIMBUKAR U. S.',
                'VD. KULKARNI A. A.',
                'Dr. R.N. Patil',
                'VD. SHITUT S. A .',
                'Dr. Udai R. Patil',
                'Dr. Ketki A. Mhaske',
                'Dr. Ajinkya Prakash Patil',
                'Dr. Riya R. Gharat',
                'Dr. Amol Eknath Mumbaikar',
                'Dr. Bhanu Y. Mulkikar,',
                'Dr. Abhitej S. Mahaske',
                'Dr. Mukesh Himmatmal Oswal',
                'Dr. Manish Pendse',
                'Dr. Arun Rai',
                'Dr. Aangha Prakash Dive',
                'Dr. Milind Goroba Chincholkar',
                'Dr. Prakash Madhukar Dive',
                'Dr. (Mrs.) Shreya Tejas Veer',
                'Dr. Tejas Pandurang Veer',
                'Dr. Sudip Chakrabarthy',
                'Dr. (Mrs.)Neelima Ajitkumar Khachane',
                'Dr. Mahendra Kumar',
                'Dr. Sanjay Barnwal',
                'Mrs.Dr. Shubha Dev Taneja',
                'Dr.Dr Ashish Santosh KhurpadeNaik',
                'Dr.Devanand Dinanath Taneja',
                'Dr.Mangesh Ramchandra Dake',
                'Mrs.Sangeeta Mangesh Dake',
                'Dr.Amol Sukhdev Giri',
                'Mr.Minal Anand Wagle',
                'Mr.Padmakar Hiru Mate',
                'Mr.Dr. Minal Anand Wagle',
                'Dr.Pratapsingh Phulsing Rathod',
                'Dr. Kishor Bhokare',
                'Dr. Aishwarya Rakhewar',
                'Dr. Atul Patil',
                'Dr. Sachin Gawand',
                'Dr.Amol Shivaji Gosavi',
                'Mr.SANTOSH BHASKAR KAMERKAR',
                'Dr.SIDDHI SANTOSH KAMERKAR',
                'Mr.AVINASH PRABHAKAR NAGPURE',
                'Dr.Padmini Shivaji Barphe',
                'Dr.Mahesh Parashuram Kadam',
                'Dr.Prashant Purkar',
                'Dr.Amol Mumbaikar',
                'Dr.Hitendra Bhirude',
                'Dr.Uttamkumar D. Shinde',
                'Dr.Kundan Rathore',
                'Mr.Vinod Dhole',
                'Mr.Sucheeth Avanti',
                'Mr.Ankur Patel',
                'Mr.Sucheeth Avanti'
            ],
            Sangli: [
                'Mr.Onkar Vilas Mali',
                'Onkar Vilas Mali',
                'Mrs.Poonam Annasaheb Upadhaye',
                'Dr.Dr. Ganeshkumar Vilasrao Bhoi',
                'Dr.Dr. Manojkumar Harishchandra I',
                'Dr.Dr. Pradip Ramchandra Landge',
                'Dr.Dr. Pranita Kondobarao Solanke',
                'Dr.Dr. Prashant Balasaheb Deshmuk',
                'Mrs.Dr. Prenjal Govind Shivade',
                'Mrs.Dr. Prenjal Govind Shivade',
                'Mr.Dr. Rajan Maruti Kamat',
                'Mrs.Dr. Ranjana Rajan Kamat',
                'Mr.Dr. Shrikant C Paramane',
                'Mr.Dr. Suhas Yashwant Joshi',
                'Mr.Dr. Sunil Pandurang Mulye',
                'Mrs.Dr. Sangita Shivajirao Deshmuk',
                'Mr.Dr. Satish Gopal Sankpal',
                'Dr.KALE RUPALI GAJANAN',
                'Dr.AMBI PRADIP BAJRANG',
                'Dr.GAWADE ROHINI RAJARAM',
                'Dr.Santosh Ramarao Patil'
            ],
            Wardha: [
                'Mr.Dr. Anil Keshavrao Wanjari',
                'Mr.Dr. Babaji Dnyaneshwar Ghewade',
                'Mr.Dr. Chandrashekhar C Mahakalka',
                'Mr.Dr. Gajanan Laxmanrao Pisulkar',
                'Mr.Dr. Vipinchandra M Kamekar'
            ],
            Pune: [
                'Vd. S.B. Rajore',
                'Vd. K.N. Bhade',
                'Vd. N.B. Goyal',
                'Vd. S.M. Todkar',
                'Vd. V.D. Taleda',
                'Vd. V.R. Hemgude',
                'Vd. V.L. Phatak',
                'Dr. Y.R. Kulkarni',
                'Vd. A.Y. Ketkar',
                'Dr. Smt. V.D. Kulkarni',
                'Vd. B.G. Dhadphale',
                'Vd. S.D. Shah',
                'Dr. D.S. Jobanputra',
                'Vd. P.A. Joshi',
                'Vd. P.B. Bhandari',
                'Dr. S.S. Damle',
                'Vd. S.S. Tiwari',
                'Vd. D.J. Wadadekar',
                'Vd. J.V. Paranjpe',
                'Dr. B.R. Agarwal',
                'Vd. Smt. J.M. Shinde',
                'Vd. Smt. J.P. Kamat',
                'Dr. V.V. Shirahattikar',
                'Vd. V.V. Bhagwat',
                'Vd. Smt. K.V. Chiplunkar',
                'Vd. T.B. Dhotre',
                'Dr. S.D. Chandekar',
                'Vd. P.B. Navgire',
                'Vd.A.V. Choudhary',
                'Vd. Smt. M.S. Bhagwat',
                'Dr. Smt. S.J. Nerlekar',
                'Dr. A.U. Pungaliya',
                'Dr. Kum. P.B. Varpe',
                'Dr. S.N. Deshpande',
                'Vd. D.G. Parkhi',
                'Vd. B.S. Keskar',
                'Vd. M.R. Satpute',
                'Vd. Smt. U.S. Gaidhani',
                'Vd. P.M. Sheth',
                'Vd. N.C. Gujarathi',
                'Dr. Prabhakar Palve',
                'Vd. Smt. R.C. Peshve',
                'Dr. R.S. Shah',
                'Vd. P.B. Londhe',
                'Dr.S.C. Ambike',
                'Dr. J.D.Avhad',
                'Vd.R.B.Rajore',
                'Dr.G.H.Mastud',
                'Dr. N.M.Vora',
                'Vd. S.S. Londhe',
                'Vd. U.P.Mate',
                'Vd.A.R. Joshi',
                'Vd. J.S.Deshpande',
                'Vd. A.D. Dandavate',
                'Vd. Smt. V.B. Patil',
                'Vd. S.V. Sangamnerkar',
                'Vd. A.M. Lingayat',
                'Vd. P.A. Date',
                'Dr. V.S. Jawale',
                'Vd. R.R. Pardeshi',
                'Vd. B.S. Chhachhia',
                'Vd. V.B. Joshi',
                'Vd. Smt. S.R. Choudhari',
                'Vd. R.G. Choudhari',
                'Vd. Smt. S.V. Wani',
                'Vd. C.B. Garudkar',
                'Dr. S.M. Patharkar',
                'Dr. M.T. Alekar',
                'Vd. R.L. Deshpande',
                'Vd. N.D. Salke',
                'Vd. R.G. Bhati',
                'Vd. A.Y. Choudhari',
                'Dr. R.R. Nipte',
                'Vd. O.V. Rudrawar',
                'Vd. U.H.Chokshi',
                'Vd Smt.M.K.Gore',
                'Vd.M.K. Ramnani',
                'Dr. smt.U.S.Dane',
                'Dr. smt.S.P. Jayshinghani',
                'Dr. Smt. R.A.Jagadale',
                'Vd. K.I.Inamdar',
                'Vd. V. P.Lole',
                'Vd. S.G. Mule',
                'Vd. A.D. Varma',
                'Vd.Smt. N.R.Mangudkar',
                'Vd. R.P.Mangudkar',
                'Vd. S.P.Mangudkar',
                'Dr. R.B.Telang',
                'Vd. Smt. P.V. Bharde',
                'Vd. A. P.Shaha',
                'Vd. V.D. Bharde',
                'Vd. N.S.Wagh',
                'Vd. Smt. S.B.Kalyankar',
                'Vd.Smt. S.B. Pharande',
                'Vd.S.H. Shaha',
                'Vd. K.V. Pawar',
                'Vd.Smt. H.R. Chandrashekhar',
                'Vd. Ashok Pandurang Rokde',
                'Vd. N.B.Bhujbal',
                'Vd.Smt. K.P.Wadekar',
                'Dr. V. L. Kajale',
                'Dr.V.D. Shiralkar',
                'Vd. K.D. Rasane',
                'Vd. M.M. Shaha',
                'Vd. H.N.Huilgolkar',
                'Vd. M.S.Dani',
                'Vd A.V. Vankhede',
                'Vd.S.N.Ghanwat',
                'Vd.P.S. Unnarkar',
                'Vd.S.N.Patil',
                'Vd. A. S. Khot',
                'Dr. C. B. Walke',
                'Dr. Smt.S.S. Mhetre',
                'Dr. S.D. Gosavi',
                'Vd. S.D. Adhav',
                'Vd Smt S.B. Galande',
                'Medical Officer, ESIS,Panel Disp.Talegoan',
                'Vd. A. R. Unkule',
                'Dr.S.V.Kanitkar',
                'Dr. A.S.Paranjpe',
                'Dr. R.H.Solanki',
                'Vd. S.D.Lunawat',
                'Vd. Smt. S.S. Kulkarni',
                'Dr.Arvindra Ramchandra Joshi',
                'Dr.Satyajeet Narayan Patil',
                'Dr.Arundhati Mangesh Lingaya',
                'Dr.Hemant Narsinh Huilgolkar',
                'Dr.Nutan Sanjay Wagh',
                'Dr.Karim Ibrahim Inamdar',
                'Dr.Sham Ghamaji Mule',
                'Dr.Satish Devidas Adhav',
                'Dr.Prakash Baburao Londhe',
                'Dr.Suhas Sitaram Londhe',
                'Dr.Arvind Yashwantrao Choudhari',
                'Dr.Swati Ravindra Choudhari',
                'Dr.Jyoti Mahadev Shinde',
                'Dr.Supriya Abhay Kulkarni',
                'Dr.Sushila Shivraj Mhetre',
                'Dr.Ramesh Himmatmal Solanki',
                'Dr.Gitangali Sandip kale',
                'Dr.Sachin Dayanand Lavane',
                'Dr.Shreeparkash Bhaskar Galande',
                'Dr.Shivanath Kashinath Shinde',
                'Dr.Nitinkumar Govardhan Jadhav',
                'Dr.Amol Manohar Shahane',
                'Mrs.Sangita Balasaheb Pharande',
                'Mr.Ashok Pandurang Rokade',
                'Mr.Keshav Vithalrao Pawar',
                'Mr.Rajendra Ganpatsingh Bhati',
                'Mrs.Purna Vasant Bharde',
                'Mr.Vasant Dattatrey Bharde',
                'Mr.Suhas Narayan Deshpande',
                'Dr.Dhondiram N.Bille',
                'Mrs.Surekha Shreekant Rangdal',
                'Dr.Neeta A. Mane',
                'Dr.Abhijit Ashok Mane',
                'Dr.Rekha Anand Jagadale',
                'Mr.Gajanan Shankarrao Shinde',
                'Mr.Subhashchandra Shivdular Tiwar',
                'Mr.Suryakant Dongarma Lunawat',
                'Mr.Prakash Atmaram Date',
                'Mr.Rajiv Balram Telang',
                'Mr.Vitthal Pandharinath Lole',
                'Mrs.Soniya Pratap Jaisinghani',
                'Mr.Jagadeesh Shankar Deshpande',
                'Mr.Ravindra Govindbhai Choudhari',
                'Mrs.Rekha Chandrashekhar Pesha',
                'Mr.Ramesh Ghevarchand Mutha',
                'Mr.Atmaram Vishram Vankhede',
                'Mr.Makarand Shriram Dani',
                'Dr.Suhas Vishnu Kanitkar',
                'Dr.Anant Shankar Paranjape',
                'Dr.Virag Arvind Kulkarni',
                'Dr.Bhushan Mohan Sali',
                'Dr.Dr. Adarsh Prabhashankar Hegde',
                'Dr.Dr. Amol Popat Misal',
                'Dr.Dr. Abhijit Yuvaraj Pawar',
                'Dr.Dr. Amol Vallabh Benke',
                'Dr.Dr. Kalyani Meshram',
                'Dr.Dr. Kiran Mukund Shingade',
                'Dr.Kirankumar Jabaji Wandhekar',
                'Dr.Dr. Mahesh Bhausaheb Sinnarkar',
                'Dr.Dr. Balaji Sopanrao Sable',
                'Dr.Dr. Mahesh Ramchandra Gorgal',
                'Dr.Dr. Mayur S Agrawal',
                'Dr.Dr. Monali Narayanrao Rajurkar',
                'Dr.Dr. Nilima Atmaram Lokhande',
                'Dr.Dr. Nitin Narayan Patil',
                'Dr.Dr. Pandit Kaluram Bhosure',
                'Dr.Dr. Digambar Baburao Mahajan',
                'Dr.Dr. Pankaj Nivrutti Bhalerao',
                'Dr.Dr. Pankaj Padmakar Kulkarni',
                'Dr.Dr. Pareshkumar S Vispute',
                'Dr.Dr. Parmeshwar Gopinath Rathod',
                'Dr.Dr. Poonam Subhash Jadhav',
                'Dr.Dr. Prakash Bhausaheb Patil',
                'Dr.Dr. Prakash Laxman Pachpute',
                'Dr.Dr. Milind Sadanand Tayde',
                'Dr.Dr. Namrata Kashinath Thorat',
                'Dr.Dr. Pankaj Nivrutti Bhalerao',
                'Dr.Dr. Pravin Bhimrao Kamble',
                'Dr.Dr. Samadhan N Kshirsagar',
                'Dr.Dr. Rahul Bharat Patil',
                'Dr.Dr. Rinkush Ram Tilokchandani',
                'Dr.Dr. Rohit Bhairawa Prasad',
                'Dr.Dr. Shashikant Vasudev Madrewa',
                'Dr.Dr. Sachin Lakshmana Nikam',
                'Dr.Dr. Sagar Anant Khadilkar',
                'Dr.Dr. Shailendra Baliram Pawar',
                'Dr.Dr. Shailesh Sakalchand Shah',
                'Dr.Dr. Sunil Shankarrao Desai',
                'Dr.Dr. Smitarani Govindrao Patil',
                'Dr.Dr. Sunil Ramchandra Deokar',
                'Dr.Dr. Sushil Jalindar Deshmukh',
                'Dr.Dr. Swaraj Fulchand Shelke',
                'Dr.Dr. Vaijanath Mohanrao Kamble',
                'Dr.Dr. Tejas Dharmraj Bhujbal',
                'Dr.Dr. Umesh Maruti Jirange',
                'Dr.Dr. Utkarsha Madhukar Budhawan',
                'Dr.Dr. Vishwajit Rajendra Chavan',
                'Dr.Dr. Yuvraj Khema Bade',
                'Dr.Dr. Bharat Dagadu Khandagale',
                'Dr.Dr. N. Ramesh',
                'Dr.Dr. Pratiksha Atul Bhalgat',
                'Mr.SANTOSH ANKUSHRAO PATHARE',
                'Mr.RAVINDRA BHASKAR JADHAV',
                'Mr.VIVEK SURESHCHANDRA GUPTA',
                'Shreeprasad Bhaskar Sidhaye',
                'SHRIKANT',
                'Shreehari',
                'Ashish',
                'Dr.Adarsh Prabhashankar Hengde',
                'Dr.Pawar Pruthviraj s',
                'Dr.Bhushan Mohan Sali',
                'Dr.Seema sachin Aiwale',
                'Dr.sachin Namdev Aiwale',
                'Dr.Tushar Agarwal',
                'Dr.Tushar Agarwal',
                'Dr.Shailesh Sakalchand Shah',
                'Dr.Shailesh Sakalchand Shah',
                'Dr.Shailesh Sakalchand Shah',
                'Dr.Shailesh Sakalchand Shah',
                'Dr.Laxmikant B. Kaotekwar',
                'Dr.Ajit Raosaheb Awati'
            ],
            Mumbai: [
                'VD. THACKAR (SMT) S.',
                'VD. SATHE (SMT.) S R',
                'VD. PRABHU (SMT) V. V.,',
                'VD. SHAH S K',
                'DR. ALPHANSO K. C,',
                'DR. DAVE. K. M.,',
                'DR. RATHORE B. S.,',
                'DR. MEHTA. B. G.,',
                'DR. GODBOLE. A. S.,',
                'DR. JOSHI. K. V.,',
                'DR. THAKKAR D. G.,',
                'I.C. PANEL DISP',
                'DR. BHAYE S. D.,',
                'DR. SUMATHI (KUM) B.',
                'DR. TENDULKAR. S .D.,',
                'DR. SHAH H .D.',
                'DR. KAWALI P.V.',
                'DR. SURLEKAR. R. V.,',
                'DR. KHARADE. S. D.',
                'DR. SHAH. K. J.,',
                'DR. SHAH. M. N.,',
                'DR. DAHAKE. (MRS) A. K.,',
                'DR. KHATRI (SMT) R. K.,',
                'DR. PATEL. M. G.',
                'DR. CASTILINO R. ALLAN,',
                'DR. SHASTRI. P. K.,',
                'DR. JAIN. P. M.,',
                'DR. ASH ER. (SMT) H. D.,',
                'DR. CHIKHALIKAR .P. A.,',
                'DR. MEHTA . B. S.',
                'DR. SHAH. J. R.',
                'DR. SHETTY B M.,',
                'DR. PRABHU M. B .,',
                'DR. PATIL P. D.',
                'DR. DOSHI B. C.',
                'DR. SONI. D. U.,',
                'DR. AGARWAL B. S.,',
                'DR. VASANDANI. S. H.,',
                'DR. MANEK A. V. ',
                'DR. TEKCHANDANI, K.G.,',
                'DR. GANDHI N. J.,',
                'DR. MEHTA J. C.,',
                'VD. NAGDA V. L.,',
                'DR. KELSHIKAR . S. V.',
                'DR. KOTECHA . N. K.,',
                'DR. MANIAR A. M.,',
                'DR. SHAH. D. B.,',
                'DR. TANDALE D. H.,',
                'DR. JOGLEKAR B. V.',
                'DR. TALAWADEKAR A. G.,',
                'DR. BARDE (SMT) S. R.,',
                'DR. KHILARI S. L.,',
                'DR. GOTPAGA R G. S.,',
                'DR. VORA . P. B.,',
                'DR. BHUTE S. S.',
                'DR. BHATT N. J.,',
                'DR. DESAI M. G.,',
                'DR. NIRMAL N. G.,',
                'DR. LAWANGARE J. R.,',
                'DR. JAWADEKAR S. P.',
                'DR. CHHEDA P. R.,',
                'DR. MAHAJAN C. B. ,',
                'DR. MAHESHWARI P. B.',
                'DR. DMELLO M. J.,',
                'DR. DHAR. A. S.,',
                'DR. LAKHANI. R. K.,',
                'DR. KAWDE R. N.,',
                'DR. PATEL A. V.',
                'DR. MEHTA G. L.',
                'DR. PANCHAL R. K.,',
                'DR. BHACHAWAT R. M.,',
                'DR. VARIAVA (MRS) J. C.,',
                'DR. GURJAR S . P.,',
                'DR. DESHMUKH S. V.,',
                'DR. PRASADE U. D.,',
                'DR. KOLTE R. H.,',
                'DR. MODY.(MRS) A. C.,',
                'DR. MEHTA. J. D.,',
                'DR. ADVANKAR K.V.,',
                'VD. BHATT J. D.',
                'VD. SANGHAVI S. J.,',
                'VD. NARULA N.,',
                'VD. REGE P. D .,',
                'VD. TIWARI (SMT) S. U.,',
                'VD. GUPTA K. B.,',
                'VD. BHAGWAT V. R.,',
                'VD. SHETTY S.N.',
                'VD. MASRANI D. D .,',
                'VD. SADHALE A. A.,',
                'VD. SHETH J. R .,',
                'VD. DHOLKIA B. K.',
                'VD. UPADHYAY M. M.',
                'VD. SHAH P. H .',
                'VD. JOSHI G. V .',
                'VD. DAMANIA J. C.',
                'VD. MEHATA R .J',
                'VD. PATIL M. B .',
                'VD. SHAHANE B. N .',
                'VD. PANDIT A. N .',
                'VD. DESHMUKH D. K .,',
                'VD. KENIA (KUM) K .S.,',
                'VD. GAUTAM H. H .',
                'VD. CHOUDHARI (SMT) S. S.',
                'VD. DUBE .R. R.',
                'VD. SANGHAVI C. A.,',
                'VD. MAVALANKAR. T .S.',
                'DR. MALBAR (SMT) N. H.',
                'DR. SHAH Y. M.,',
                'DR. LAD (SMT) M. D.,',
                'DR. LAWANDE S. G.,',
                'DR. SHAH (SMT) H. C..,',
                'DR. MODY. H. K.,',
                'DR. CHAUHAN R. R.',
                'DR. BHARATI (SMT) D. H.',
                'VD. SAMBARI S .R .',
                'DR. TAMANE P. M.,',
                'DR. KAMBLI C. S. ,',
                'VD. TAGARE (KUM) K.R.,',
                'DR. JAIN S. L.,',
                'DR. JAIN M. K.,',
                'VD. SHIVJIYANI T. M.,',
                'DR. LAKHANI M. J.,',
                'DR. WADE V. .A.,',
                'VD. MODY D. K.,',
                'DR. SANGHAVI K. B',
                'DR. SANGHAVI K. B',
                'DR. KAMAT M. N.,',
                'DR. KAMATH. P . N.,',
                'DR. AZAD U.S',
                'DR. SHEKAR (SMT) P. C.,',
                'DR. GHATALIA M. P.,',
                'VD. KAMAT S. D.',
                'VD. WAGALE A.T.',
                'VD. BIJOOR .M. B.,',
                'DR. BANSI J. K.,',
                'DR. PATWARDHAN. S .D.,',
                'DR. NANAVATI. M. S.,',
                'DR. SHAH. P.D.',
                'DR. SUKHATANKAR. R. D.,',
                'DR. V.S. PAREKH.',
                'DR. PAREKH (SMT) M. J .',
                'DR. PATEL R V',
                'DR. DEDHIA. M. D.,',
                'DR. PRABHU S. R. ,',
                'DR. DADHICH. B. K.',
                'DR. KHARA. S.K.',
                'DR. DESAI. K. M.,',
                'DR. SMT RANE V.R.',
                'DR. HIRANI J . H.,',
                'DR. TRIVEDI S. L.,',
                'DR. SHAH (SMT) S. R. ,',
                'DR. VELANI I. P.,',
                'DR. GOR. V.J.',
                'DR. WORLIKAR A. K.,',
                'DR. VINCHHI B. K.,',
                'KALINA AIR INDIA STAFF',
                'Dr. SHENOY S.R.',
                'DR. RAGATE U. V.,',
                'DR. PATEL A. L.,',
                'DR. SIDHAWA M. R.,',
                'DR. SURU. J.T.',
                'DR. NAYAK S. M.,',
                'DR. MEDHEKAR S. N.,',
                'DR. SHAH N. K.,',
                'DR. TIPRE M B',
                'DR. PANCHAL H. M.,',
                'DR. JOSHI K.B.',
                'DR. SALUNKHE P. S.,',
                'VD. BHAVASAR A.H.',
                'DR. DADHICH. B. K. ,',
                'VD. PATIL. (SMT) U.S.',
                'VD. DALAL B. I .,',
                'VD. SHAH S M',
                'VD. KUMBHAR Y. V .,',
                'VD. SHAH R. M.,',
                'VD. GUPTA R. P .,',
                'VD.KUM KAPADIA V.R.',
                'VD. VHADGE H. V .',
                'VD. SHAH. D.B.',
                'VD. YEOLE B M',
                'VD. SOMANI R. S .',
                'VD. JANI V .M .',
                'VD. CHAUDHARI D. K.',
                'VD. LOKHANDE N. D .',
                'VD. THAKKAR H. G.',
                'VD. DESHPANDE C.G.',
                'VD. TRIVEDI J. B .,',
                'VD. DESAI P .N .',
                'VD. PANDIT R. D.',
                'VD. YADAV C. N .',
                'VD. SHUKLA D. C .',
                'VD. BHOITE B. J .',
                'VD. PANDHYA V.H.',
                'VD. JOSHI S. P .',
                'VD. SALVI J. G .',
                'VD. PANDEY M. H .,',
                'VD. BHAGAT C. J.',
                'VD. KUDKE V. N .',
                'VD. KATKAR (SMT) V. J.',
                'VD. DAHIVALE A. A.',
                'VD. MULYE V. G.)',
                'VD. SINGH J. B.',
                'VD. SHETYE (SMT ) S. D.',
                'VD. MEHENDALE S. V.',
                'VD. MAMNIA (KUM) L. M.,',
                'VD. SHANBHAG S. G.,',
                'VD. PEDNEKAR (SMT) S. A.',
                'VD. DHABALIA V. H.',
                'VD. NIGAM R. K.',
                'VD. PRASAD I. L.',
                'VD.UCHGAONKAR(KUM)V. B.',
                'VD. KULKARNI R. A.,',
                'VD. GHELANI J. P.,',
                'VD. KOTHARI J. M.,',
                'VD. SAWANT (SMT) H. B.',
                'VD. NAIK S. V',
                'VD. BHANDAR (SMT) R. S.',
                'VD. BORIKAR S. P.,',
                'VD. MOTANI D. K .',
                'VD.SURAJESINGH ISHERSINGH',
                'VD. GUPTA M. P.,',
                'VD.KANSUPADA(SMT) M.K.',
                'VD. SHAH S. J.,',
                'VD. BAISKAR M. G.',
                'VD. SHETE A. R.,',
                'VD. KARANJKAR P . V.,',
                'VD. KHODANI T. N.,',
                'VD. THAKAR D. P.,',
                'VD. PAREKH P. J.,',
                'VD. GUPTA R. R., (DSAC)',
                'VD. RAVAL N. L.,',
                'VD. VINCHHI ( SMT) D. B.',
                'VD. DEDHIA D. M.',
                'VD. DADHICH J. K.',
                'VD. MHATRE G. E.',
                'VD. JOSHI D. S.',
                'VD. MAKWANA R. V.',
                'VD. TURKEWADIKAR S. B . ,',
                'VD. KHOMBADIA A. V.,',
                'VD. DESAI A. O.',
                'VD. THAKAR V. N.',
                'VD. NAIK A. B.',
                'VD. DEDHIA (KUM) J. H.',
                'VD. SHETE (SMT) S. A.,',
                'VD. LIMBCHIYA M. M.,',
                'VD. VYAS N. K.',
                'VD. SHARMA V. C.',
                'VD. BHAVSAR A. O.',
                'VD. DOSHI. S A',
                'VD. KAWATKAR A.S.',
                'VD. MODEY (SMT) P. J.,',
                'VD. SHETH C. M.',
                'VD. SHAH A. N.',
                'VD. VAZE P. V.',
                'VD. MODY C. P.',
                'VD. RANA M. C.',
                'VD. MESWANI. D.F.',
                'VD. ADSULE D. B .',
                'VD. RAVLE D.S.',
                'VD. JOSHI A. G.',
                'VD. WADAMBE . V G',
                'VD. BELOSE R. G.',
                'VD. TAMBE S. S.',
                'VD. KAJBAJE (KUM) V. P.',
                'DR. DADHICH. B. K. ,',
                'VD. SALVI A.M.',
                'VD. ADSULE (SMT) M. D.',
                'VD. PUSALKAR R. V.,',
                'VD. SHAH S. B.',
                'VD. SHAH B. M.',
                'VD. JADHAV (SMT) R. A.,',
                'VD. SHAH B. C.',
                'VD. MEHTA H. C.',
                'VD.BHANUSHALI (SMT) K. D',
                'VD. PHADKE S. G.',
                'VD. THODA A. K',
                'VD. BHALERAO (SMT) S. S. ,',
                'VD. NIMBALKAR A. G. ,',
                'VD. KHEDEKAR (SMT) S. S.',
                'VD. KHADTARE (SMT) V. G.',
                'VD. SHARMA R. B.',
                'VD. MALPANI K. S.',
                'VD. SHAH P. S.',
                'VD. GHUNDIYAL N. M.',
                'VD. CHAUBE C. M.',
                'VD. PEDGAOKAR N. M.',
                'VD. TAWA R I A. R.',
                'VD. TAWARI J. K.',
                'DR. DADHICH. B. K. ,',
                'VD. POPHALE S. M. ,',
                'VD. DICHWALKAR (SMT) S. P.',
                'VD. VAZE S. N.',
                'VD. DADHICH S. P.',
                'VD. SINGH B. R.',
                'VD. ATHANI (MRS.) M. S.',
                'VD. RANE P .N.',
                'VD. KUBADE M. M.',
                'VD. UMALKAR S. M.',
                'VD. PATIL R. D.',
                'VD. GHOSALKAR (SMT)P. S .',
                'VD. MULE M .D.',
                'VD. DESHMUKH (SMT) S. S',
                'VD. YADAV N. D.',
                'VD. YADAV V. R.',
                'VD. BHADLE A. H.',
                'VD. SINGH R. M.',
                'VD. GUPTA R. K.',
                'VD. POL R. V.',
                'VD. GADE. M G.',
                'VD. SOLANKI P.M.',
                'VD. KADAM R. G.',
                'VD. SINGH H. D .',
                'VD. SINGH A. K.',
                'VD. SAWANT S. S.',
                'VD. WANI J. S.',
                'VD. DANGI R. D.',
                'VD. GAUTAM A. J.',
                'VD. NARKAR M. D.',
                'VD. PANDIT R. K.',
                'VD. CHAVAN A. D.',
                'VD. PATIL V. C.',
                'VD. SAMANT CHANDRASHEKAR',
                'VD. PRABHUDESAI V. P.',
                'VD. YADAV P. M.',
                'VD. YADAV C. R.',
                'VD. SHINDE S. N.',
                'VD. KALE S. L.',
                'VD. MISHRA S. T.',
                'VD. SINGH J. D.',
                'VD. MAHAJAN S. P.',
                'VD. SINGH A. S.',
                'VD. VARMA R. R.',
                'VD. DHAR (MRS) N. A.',
                'VD. PARMAR C. M.',
                'VD. SHAH B. R.',
                'VD. MISHRA A. R.',
                'VD. RAUT. K. P.',
                'VD. PATEL. M. M.',
                'VD. PATEL M. C.',
                'VD. PATEL. S. S.',
                'VD. NISHAD V. T.',
                'VD. SHETH A. L.',
                'VD. GODSE Y. D.',
                'VD. JOSHI P. M.',
                'VD. PARULEKAR R. S.',
                'VD K.B.GOUD',
                'VD. JOSHI D. W.',
                'VD. PARAB (MRS) S. P.',
                'VD. DUBEWAR V. M.',
                'VD. SAWANT A. I.',
                'VD. PARAB P. R.',
                'VD. SHAH R. P.',
                'VD. SAMANT S. M.',
                'VD. TRIPATHI P. S.',
                'VD. MISHRA S. R.',
                'VD. RAI V. C.',
                'VD. RAI J. K.',
                'VD. DEORE M. S.',
                'VD. CHAUBE S. K.',
                'VD. MISHRA D. P.',
                'VD. SINGH A. S.',
                'VD. RAI K. S.',
                'VD. GUPTA R. B.',
                'VD. GUPTA V. R.',
                'VD. (Smt) VAIDYA T. R.',
                'VD. MRS BABTIWALA A.K.',
                'VD. CHOWDHARY (MRS) S. A .',
                'VD. BANDEKAR U. B.',
                'VD. SINGH J. S.',
                'VD. YADHAV S. S',
                'VD. YADAV. G. D.',
                'VD. TRIPATHI R. A.',
                'VD. SINGH (SMT) P. T.',
                'VD. GAWLI V. D.',
                'VD. CHATURVEDI M. M.',
                'VD. NERLEKAR . K. T.',
                'VD. DESHPANDE (MRS) V. V.',
                'VD. YADAV (MRS) V. R.',
                'VD. SONAR. R. R.',
                'VD. SINGH V. I.',
                'VD. DWIVEDI A. R.',
                'VD. PATIL. (MRS) U. C.',
                'VD. DAMLE A. V.',
                'VD. SAWANT R. S.',
                'VD. YADAV L. T.',
                'VD. HALURKAR S. D.',
                'VD. SURYAWANSHI A. S.',
                'VD. KHER V. G',
                'VD. WAGHMARE (KUM) N. S.',
                'VD. MANE P. N.',
                'VD. YADAV R. R.',
                'VD. MISHRA. A.D.',
                'VD. KHANOLKAR M.N.',
                'VD. KINI. J. S.',
                'VD. SINGH S. D.',
                'VD. PAWAR B. D.',
                'VD. JAYASWAL S. N.'
            ],
            Thane: [
                'DR. DEVARSHI. P. A.,',
                'DR. EKLAHARE S. D.,',
                'DR. DESHPANDE S.',
                'DR. TANNU .V',
                'DR. NARENDRANATH.M.N.',
                'DR. SHRINGARPURE J.',
                'DR. KHOPKAR. (SMT) L. P.',
                'DR. VAIDYA S.',
                'DR. RAISINGHANI J.',
                'DR. WANI M.',
                'DR. PUNYARTHI R',
                'DR. THAKUR (SMT) J. P.,',
                'DR. KALANI V. D.,',
                'DR. GHUMARE P. K.,',
                'DR. DAPTARDAR A. S.,',
                'DR. KHARATMAL S. N.,',
                'DR. PRADHAN A. G.,',
                'DR. PANCHAL P. H.,',
                'DR. MANKAME A.',
                'DR. CHOKSHI S. .Y.,',
                'DR. SHENDARKAR P. V.,',
                'DR. DHALE M.',
                'DR. THAKKAR. K. N.,',
                'DR.SHENDARKAR (MRS) P. P',
                'DR. SINGH',
                'DR. RAUT. D. M.',
                'DR. KALANTARE. D. D.,',
                'VD. MAHAJAN K. B',
                'VD. SHEJWALKAR N. V .,',
                'VD. PRADHAN C.',
                'VD. GANDHI B. W',
                'VD. JAEEL G.',
                'VD. SAHANI (SMT.)R.',
                'VD. PANDIT V.',
                'DR. KORDE .(SMT) A. A.,',
                'DR. SHENOY K.',
                'DR. PATIL P.',
                'DR. SHUKLA B . N.,',
                'VD. KULKARNI S. K',
                'DR. DHAMADE A. M.,',
                'DR. MISHRA R.',
                'DR. SUTARIA K. V.,',
                'DR. KHOPKAR U. J.,',
                'DR. JOSHI . D.',
                'M/O i/c',
                'DR. THAKKAR',
                'DR. SINHA.',
                'DR. CHITNIS K.',
                'DR. KRISHNAN S.',
                'DR. CHIKODI B. V.,',
                'DR. PADHYE P.',
                'DR. JAIN R.',
                'DR. NATHANI (MRS)',
                'DR. NAIK. M.',
                'DR. KAUSHIK.',
                'DR.SAHAKARI.',
                'VD. RAJE A. D',
                'VD. KARNIK S. B',
                'VD. JADHAV',
                'VD. JOSHI.',
                'VD. JOG.',
                'VD. JOG H .R',
                'VD. PANSHIKAR',
                'VD. THACKER',
                'VD. JOSHI M. D',
                'VD. BHADKAMKAR A.',
                'VD. THAKKAR P. P .',
                'VD. ARBAT M. S',
                'VD. MANGEA I. O,',
                'VD. SACHDEVANI G. V.',
                'VD. LATKAR P.',
                'VD. KHARKAR (SMT ) N. A.',
                'VD. SHAH V.',
                'VD. PATIL A. B.',
                'VD. CHAUMAL P. V.,',
                'VD. PATEL M.',
                'VD. KHATALE C. V.,',
                'VD. CHAUMAL R',
                'VD. APTE V. S.',
                'VD. DEODHAR V. R.',
                'VD. SACHDEVANI S. W.,',
                'VD. DIWATE (SMT) S. S.,',
                'VD. SAMEL V. D.',
                'VD. JOSHI K. B.',
                'VD. DESHPANDE J. S. ,',
                'VD. TAVKAR S. N .',
                'VD. NARAVANE C. G. ,',
                'VD. JOGLEKAR M. P.,',
                'VD. SANGHAVI A. P.',
                'VD. VICHARE (SMT) V. V.,',
                'VD. THAKUR B. S.,',
                'VD. SINKAR A. P.',
                'VD. VORA A. R.',
                'VD. SHAH S. K.',
                'VD. BHAGWAT D. .B. ,',
                'VD. JOSHI ( SMT) R. V.',
                'VD. HORE A. A.',
                'VD. CHHAJED R. B.',
                'VD. SHAH M. P.',
                'VD. RAJPUT R. G.',
                'VD. MAHAJAN G.',
                'VD. CHIPKAR A. Y.',
                'VD. SATHE (SMT) A. A.',
                'VD. AVAD C.',
                'VD. SAWANT S.',
                'VD. MALSHE G. S.',
                'VD. DASS S. L.',
                'VD.(Kum)',
                'VD. KHANDELWAL V.',
                'VD. TAWARI H.',
                'VD. BHOJANE G.',
                'VD. JOGLEKAR (SMT) M.',
                'VD. KADAM A. U.',
                'VD. JAWALE A. P.',
                'VD. PAWAR S. P .',
                'VD. TENDLE V. C.',
                'VD. RAMSINGH V. P.',
                'VD. BHOLE P. K.',
                'VD. SINGH KEDARNATH.',
                'VD.PENDBHAJE (SMT) D. M.',
                'VD. TIWARI V.',
                'VD. MUZUMDAR (SMT) S.',
                'VD. BHAVSAR N. C.',
                'VD. KHAN M. G. L.',
                'VD. KHERDEKAR A. P.',
                'VD. JADHAV (SMT) B. B',
                'VD. GUPTE S.',
                'VD. YADAV M.',
                'VD. SAINDANE P. A.',
                'V.D. AHIRE',
                'VD. HANDE S. S.',
                'VD. MORE .A. D.',
                'VD. KOLTE .P. R.',
                'VD. JOSHI.(SMT) S. S.',
                'VD. CHAUMAL M . R.',
                'VD. PATGAONKAR S. H.',
                'VD. KITHANI M. V.',
                'VD. KANAKIYA N. R.',
                'VD. KANAKIYA (MRS) V. M.',
                'VD. KUMBHAR (MRS) N. A.',
                'VD. TRIPATHI N. U.',
                'VD. WANI S. D.',
                'VD. RAUT B.',
                'VD. UMAL M. K.',
                'VD. KULKARNI A. A.',
                'DR. KHADATKAR S.',
                'VD. JOSHI U. N.',
                'VD.THAKUR',
                'VD. SALI K.',
                'VD. NEPHADE U.',
                'VD. TIPARE N. K.',
                'VD. GHUGE S. T.',
                'VD. JANGLE A.',
                'VD. POTDUKHE S.',
                'VD. GUPTA V.',
                'VD. PAWAR.J.K',
                'VD. NISHANDAR',
                'VD. BHASAGARE A. D.',
                'VD. PATWARDHAN (SMT) A. S.',
                'VD. NATHANI. K.',
                'VD. SINGH A. T.',
                'VD. RANE R. P.',
                'VD. SAWANT R.',
                'VD. KSHIRSAGAR R. L.',
                'VD. PATIL L.',
                'VD. GUPTA R.',
                'VD. GAIKWAD (MRS) V. A.',
                'VD. PAWAR H.',
                'VD. PANDEY J. P.',
                'VD. DHONDE. C. N.',
                'VD. KHANDGE. G. D.',
                'VD. PATIL A. E.',
                'VD. PAWAR. D. M.',
                'VD. SINGH (MRS) G. D.',
                'VD. MISHRA R.',
                'VD. DEOSTHALI A. M.',
                'VD. SHUKLA. A. K.',
                'VD. SALVE P. V.',
                'VD. YADAV M. R.',
                'VD. WAINGANKAR S. A.',
                'VD. GUPTE. S. P.',
                'VD. PATIL V.',
                'VD. RANE (MRS) H. S.',
                'VD. KULKARNI. G. H.',
                'VD. GUPTE. A. A.',
                'VD. DUBEY S. R.',
                'VD. THAKKAR M. S.',
                'VD. SHINDE U. C.',
                'VD. VELEKAR V. M.',
                'VD. PATIL D.',
                'VD. SALUNKE S. B.',
                'VD. SINGH S. J.',
                'VD. DANGE B. S.',
                'VD. SINGH J.',
                'VD. LAUHAR R. U. /RAJBHATT',
                'VD. SMT BAWASKAR',
                'VD. UJJANKAR MOHAN',
                'VD. BHAGAT (MRS) J. V.',
                'VD. KHATAVKAR R.',
                'VD.KAPARKAR',
                'VD. DASARE V.',
                'VD. SME KUNTE G',
                'VD. PARAB P. P.',
                'VD. KODIYAL G. K.',
                'VD. MHATRE V.',
                'DR. MANOJ',
                'VD. (MRS) A. A.',
                'VD. GOUDA'
            ]
        }
    },
    Dispensary: {
        Karnataka: {
            Bagalkot: ['Bagalkot, KA (ESIS Disp.)', 'Banahatti, KA (ESIS Disp.)', 'DCBO - Bagalkote'],
            Bangalore: [
                'Wilson Garden',
                'KA (ESIS Disp.)',
                'Attibelle, KA (ESIS Disp.)',
                'Banashankari, KA (ESIS Disp.)',
                ' Binnypet, KA (ESIS Disp.)',
                ' Bommanahalli, KA (ESIS Disp.)',
                ' Bommasandra, KA (ESIS Disp.)',
                'Channapatna, KA (ESIS Disp.)',
                'Cottonpet, KA (ESIS Disp.)',
                'Dasarahalli, KA (ESIS Disp.)',
                ' Dodaballapura, KA (ESIS Disp.)',
                'Dyavasandra, KA (ESIS Disp.)',
                'Frazer Town, KA (ESIS Disp.)',
                'Hanumantha Nagar, KA (ESIS Disp.)',
                'Hoskote, KA (ESIS Disp.)',
                'Jalahalli, KA (ESIS Disp.)',
                'Jayanagar, KA (ESIS Disp.)',
                'Jigani, KA (ESIS Disp.)',
                'K R Puram I, KA (ESIS Disp.)',
                'ESID Mallur, KA (ESIS Disp.)',
                'Kengeri, KA (ESIS Disp.)',
                'Konanakunte, KA (ESIS Disp.)',
                'Magadi, KA (ESIS Disp.)',
                'K R Puram II, KA (ESIS Disp.)',
                'Nelamangala, KA (ESIS Disp.)',
                'Peenya, KA (ESIS Disp.)',
                'R.T.Nagar, KA (ESIS Disp.)',
                'Rajajinagar II, KA (ESIS Disp.)',
                'Rajajinagar I, KA (ESIS Disp.)',
                'Russel Market, KA (ESIS Disp.)',
                'Sheshadripuram, KA (ESIS Disp.)',
                'Singasandra, KA (ESIS Disp.)',
                'Sriramapuram, KA (ESIS Disp.)',
                'Subramanyapura, KA (ESIS Disp.)',
                'Ulsoor, KA (ESIS Disp.)',
                'Vijayanagara, KA (ESIS Disp.)',
                'Vishwaneedam, KA (ESIS Disp.)',
                'Viveknagar, KA (ESIS Disp.)',
                'White field dispensary, KA (ESIS Disp.)',
                'Yelahanka, KA (ESIS Disp.)',
                'Yeshwanthapura, KA (ESIS Disp.)',
                'K R Puram II, KA (ESIS Disp.)',
                'Mysore road, KA (ESIS Disp.)',
                'K R Puram I, KA (ESIS Disp.)',
                'Rajajinagar I, KA (ESIS Disp.)',
                'Rajajinagar II, KA (ESIS Disp.)',
                'Wilson Garden, KA (ESIS Disp.)',
                'JINDAL Dispensary',
                'White field, KA (ESIS Disp.)',
                'ESID Mallur, KA (ESIS Disp.)',
                'Ammasandra Cement Factory, KA (ESIS Disp.)',
                'Jindal Factory Premises, KA (ESIS Disp.)',
                'Basavanagudi, KA (ESIS Disp.)',
                'Madanyakanahalli, KA (ESIS Disp.)',
                'RML College, Gottigere, KA (ESIS Disp.)',
                'Laggere, KA (ESIS Disp.)',
                'Devanahall, KA (ESIS Disp.)',
                'DCBO - Biharsharif]'
            ],
            'Bangalore Rural': ['BELHospital, KA (ESIS Disp.)'],
            Belgaum: [
                'Anandawadi, Belgaum, KA (ESIS Disp.)',
                'Gokak, KA (ESIS Disp.)',
                'K.S.R.T.C. Belgaum, KA (ESIS Disp.)',
                'Peeranwadi, Belgaum, KA (ESIS Disp.)',
                'Udayambagh, Belgaum, KA (ESIS Disp.)',
                'Yamunapura, KA (ESIS Disp.)',
                'Konnur, KA (ESIS Disp.)',
                'Nippani, KA (ESIS Disp.)'
            ],
            Bellary: ['Bellary, KA (ESIS Disp.)', 'T.B.Dam, KA (ESIS Disp.)', 'EUD - Toranagallu'],
            Bidar: ['DCBO - Bidar'],
            Chamarajanagar: ['DBO - Chamarajanagar'],
            Chickmagalore: ['DCBO - Chikkamagaluru'],
            Chickballapura: ['DCBO-Chikballapur'],
            Chitradurga: ['Chitradurga, KA(ESIS Disp.)', 'Chitradurga, KA(ESIS Disp.2)'],
            'Dakshina Kannada': [
                'Karangalpadi, KA (ESIS Disp)',
                'Kulshekar,  KA (ESIS Disp)',
                "Margan's,  KA (ESIS Disp)",
                'Panambur,  KA (ESIS Disp)',
                'Puttur,  KA (ESIS Disp)'
            ],
            Davangere: ['Davangere City, KA (ESIS Disp)', 'K.B.Extension, Davangere, KA (ESIS Disp)', 'Harihara, KA (ESIS Disp)'],
            Dharwad: [
                'Dharwad, KA (ESIS Disp)',
                'Belur, KA (ESIS Disp)',
                'Tarihat, KA (ESIS Disp)',
                'Hubli-I, KA (ESIS Disp)',
                'Varur Dispensary KA (ESIS Disp)',
                'Gokul Road, Industrial Area Hubli, KN (ESIS Disp.)'
            ],
            Gadag: ['Gadag, KA (ESIS Disp.)', 'Hulikote, KA (ESIS Disp.)'],
            Hassan: ['Hassan, KA (ESIS Disp.)'],
            Kalburgi: [
                'M.S.K.Mills, Gulbarga, KA (ESIS Disp.)',
                'Sedam, KA (ESIS Disp.)',
                'Shahabad Town, KA (ESIS Disp.)',
                'Malkhed, KA (ESIS Disp.)',
                'Wadi, KA (ESIS Disp.)'
            ],
            Kodagu: ['DCBO - Kodagu'],
            Kolar: ['Robertsonpet, KA (ESIS Disp.)'],
            Koppal: ['17 MIG 2, KHB Colony, Koppal, KN (ESIS Disp.)'],
            Mandya: ['Maddur, KA (ESIS Disp.)', 'Belagola, KA (ESIS Disp.)', 'Mandya, KA (ESIS Disp.)'],
            Mysore: [
                'Belawadi, KA (ESIS Disp.)',
                'Brindawan, KA(ESIS Disp.)',
                'Hunsur, KA (ESIS Disp.)',
                'Mysore Central, KA (ESIS Disp.)',
                'Mysore South, KA (ESIS Disp.)',
                'N.R.Mohalla, KA (ESIS Disp.)',
                'V.V.Puram, KA (ESIS Disp.)',
                'Nanjangud, KA (ESIS Disp.)',
                'T.Narasipura, KA (ESIS Disp.)'
            ],
            Raichur: ['Raichur, KA (ESIS Disp.)'],
            Ramanagar: ['Ramanagara, KA (ESIS Disp.)', 'Bidadi,KA(ESIS Disp.)'],
            Shimoga: [
                'Shimoga, KA (ESIS Disp.)',
                'Bhadravathi, KA (ESIS Disp.)',
                'MACHENAHALLI, KA (ESIS Disp.)',
                'NR Road, Shimoga, KN (ESIS Disp.)',
                'Vinobhanagar, shimoga, KN(ESIS Disp)'
            ],
            Tumkur: ['Kunigal, KA (ESIS Disp.)', 'Tumkur, KA (ESIS Disp.)', 'Tiptur, KA (ESIS Disp.)'],
            Udupi: ['Manipal, KA (ESIS Disp.)', 'Karkala, KA (ESIS Disp.)', 'Kundapura, KA (ESIS Disp.)', 'Udupi, KA (ESIS Disp.)'],
            'Uttar kannada': ['Dandeli,KA(ESIS Disp.)', 'DCBO - Karwar'],
            Vijayapur: ['Bijapur, KA(ESIS disp.)']
        },
        Telangana: {
            Godavari: ['Godavari, AP(ESIS Disp.)', 'Godavari, AP(ESIS Disp.2)'],
            Krishna: [
                'krishna, KA (ESIS Disp)',
                'krishna,  KA (ESIS Disp)',
                "Margan's,  KA (ESIS Disp)",
                'Panambur,  KA (ESIS Disp)',
                'Puttur,  KA (ESIS Disp)'
            ],
            Hyderabad: [
                'Ameerpet, AP (ESIS Disp.)',
                'Balanagar (New), AP (ESIS Disp.)',
                'Sanat Nagar-III, AP (ESIS Disp.)',
                'Balanagar (Old), AP (ESIS Disp.)',
                'Borabanda, AP (ESIS Disp.)',
                'Chappal Bazar, AP (ESIS Disp.)',
                'Chikkadapally, AP (ESIS Disp.)',
                'Chilkalguda, AP (ESIS Disp.)',
                'Dabeerpura, AP (ESIS Disp.)',
                'Yakuthpura, AP (ESIS Disp.)',
                'Golconda, AP (ESIS Disp.)',
                'Nampally, AP (ESIS Disp.)',
                'Karwan, AP (ESIS Disp.)',
                'Himmathpura, AP (ESIS Disp.)',
                'Khairatabad, AP (ESIS Disp.)',
                'Kavadiguda (New), AP (ESIS Disp.)',
                'Vidya Nagar, AP (ESIS Disp.)',
                'Ramanthapur, AP (ESIS Disp.)',
                'Old City Ramakrishna cly, AP (ESIS Disp.)',
                'Ranigunj (New) Alwal, AP (ESIS Disp.)',
                'Rezimental Bazar, AP (ESIS Disp.)',
                'Secunderbad, AP (ESIS Disp.)',
                'Sanathnagar-I, AP (ESIS Disp.)',
                'Sanathnagar-II, AP (ESIS Disp.)',
                'Tarnaka, AP (ESIS Disp.)',
                'Kukatpally, AP (ESIS Disp.)',
                'Kavadiguda, AP (ESIS Disp.)',
                'Kavadiguda Road, AP (ESIS Disp.)',
                'Moulali, AP (ESIS Disp.)',
                'Malkajgiri, AP (ESIS Disp.)',
                'Shamshabad, AP (ESIS Disp.)',
                'Ameerpet, AP (ESIS Disp.)',
                'Dabeerpura, AP (ESIS Disp.)',
                'Sanathnagar-II, AP (ESIS Disp.)',
                'Sanathnagar-III, AP (ESIS Disp.)',
                'Kavadiguda (New), AP (ESIS Disp.)',
                'Ramnagar, AP (ESIS Disp.)',
                'Rezimental Bazar, AP (ESIS Disp.)',
                'Balanagar(Old), AP (ESIS Disp.)',
                'Chikkadapally, AP (ESIS Disp.)',
                'Golconda, AP (ESIS Disp.)',
                'Himmathpura, AP (ESIS Disp.)',
                'Chappal Bazar, AP (ESIS Disp.)',
                'Karwan, AP (ESIS Disp.)',
                'Khairatabad, AP (ESIS Disp.)',
                'Kukatpally, AP (ESIS Disp.)',
                'Yakuthpura, AP (ESIS Disp.)',
                'Malkajgiri, AP (ESIS Disp.)',
                'Kavadiguda Road, AP (ESIS Disp.)',
                'Nampally, AP (ESIS Disp.)',
                'Ramanthapur, AP (ESIS Disp.)',
                'Old City Ramakrishna cly, AP (ESIS Disp.)',
                'Sanathnagar-I, AP (ESIS Disp.)',
                'Balanagar (New), AP (ESIS Disp.)',
                'Borabanda, AP (ESIS Disp.)',
                'Tarnaka, AP (ESIS Disp.)',
                'Vidya Nagar, AP (ESIS Disp.)',
                'Basanthnagar, AP (ESIS Disp.)',
                'Moulali, AP (ESIS Disp.)',
                'Kavadiguda, AP (ESIS Disp.)',
                'Chilkalguda, AP (ESIS Disp.)',
                'Secunderbad, AP (ESIS Disp.)',
                'Balanagar (New), AP (ESIS Disp.)',
                'Devapura, AP (ESIS Disp.)'
            ],
            Karimnagar: [
                'Ramagundam, AP (ESIS Disp.)',
                'Dasanthnagar, AP (ESIS Disp.)',
                'Fathenagar, AP (ESIS Disp.)',
                'Cherlapally, AP (ESIS Disp.)',
                'Jeedimetla-I, AP (ESIS Disp.)',
                'Jeedimetla-II, AP (ESIS Disp.)',
                'Koheda, AP (ESIS Disp.)',
                'Medchal, AP (ESIS Disp.)'
            ],
            Khamman: ['Ramavaram, AP (ESIS Disp.)', 'Khamman, AP (ESIS Disp.)', 'Industrial Estate, AP (ESIS Disp.)'],
            'Komaram Bheem Asifadad': ['DCBO - Sirpurkaghaznagar'],
            Mahbubnagar: [
                'Kothur, AP (ESIS Disp.)',
                'Mahaboobnagar, AP (ESIS Disp.)',
                'Bollaram, AP (ESIS Disp.)',
                'Bonthapally, AP (ESIS Disp.)',
                'Isnapur, AP (ESIS Disp.)',
                'Patancheru, AP (ESIS Disp.)',
                'Patighanapur, AP (ESIS Disp.)',
                'Sadasivpet, AP (ESIS Disp.)',
                'Shabashpally, AP (ESIS Disp.)',
                'Zaheerabad, AP (ESIS Disp.)',
                'Bibinagar, AP (ESIS Disp.)',
                'Choutuppal, AP (ESIS Disp.)',
                'Bhongir, AP (ESIS Disp.)',
                'Shivajinagar, AP (ESIS Disp.)',
                'Nizamabad, AP (ESIS Disp.)',
                'Shamshabad, AP (ESIS Disp.)',
                'Jadcharla, AP (ESIS Disp.)',
                'BALANAGAR(MBNR)',
                'DCBO - Mahaboobnagar'
            ],
            Medak: [
                'Bollaram, AP (ESIS Disp.)',
                'Bonthapally, AP (ESIS Disp.)',
                'Isnapur, AP (ESIS Disp.)',
                'Patancheru, AP (ESIS Disp.)',
                'Patighanapur, AP (ESIS Disp.)',
                'Shabashpally, AP (ESIS Disp.)',
                'Sadasivpet, AP (ESIS Disp.)',
                'Zaheerabad, AP (ESIS Disp.)'
            ],
            Nalgoda: ['Bhongir, AP (ESIS Disp.)', 'DCBO-Bibinagar, AP (ESIS Disp.)', 'Choutuppal, AP (ESIS Disp.)', 'MIRYALAGUDA'],
            Nizamabad: ['Nizamabad, AP (ESIS Disp.)', 'Shivajinagar, AP (ESIS Disp.)', 'DCBO - Nizamabad'],
            Peddapalli: ['DCBO - Ramagundam'],
            Rangareddy: [
                'Fathenagar, AP (ESIS Disp.)',
                'Jeedimetla-I, AP (ESIS Disp.)',
                'Koheda, AP (ESIS Disp.)',
                'Jeedimetla-II, AP (ESIS Disp.)',
                'Kattedan, AP (ESIS Disp.)',
                'Medchal, AP (ESIS Disp.)',
                'Cherlapally, AP (ESIS Disp.)',
                'Ranigunj (New) Alwal, AP (ESIS Disp.)',
                'SHAMEERPET',
                'IDA CHERLAPALLY',
                'DCBO - L.B.Nagar'
            ],
            Sangareddy: ['DCBO - Sadashivpeta'],
            Warangal: [
                'Hanmakonda, AP (ESIS Disp.)',
                'Girmajipet, AP (ESIS Disp.)',
                'Industrial Colony, AP (ESIS Disp.)',
                'Kareemabad, AP (ESIS Disp.)',
                'Girmajipet, AP (ESIS Disp.)',
                'Hanmakonda, AP (ESIS Disp.)',
                'Industrial Colony, AP (ESIS Disp.)',
                'Kareemabad, AP (ESIS Disp.)',
                'DCBO - Warangal'
            ]
        },
        Maharashtra: {
            Akola: [
                'D 2 Akola Harihar Peth, MH (ESIS Disp.)',
                'D 3 MIDC Akola, MH (ESIS Disp.)',
                'D 1 Ramdas Peth, Akola, MH (ESIS Disp.)'
            ],
            Amrawati: ['Amravati, MH (ESIS Disp.)'],
            Aurangabad: [
                'D 4 Chikalthana, Aurangabad, MH (ESIS Disp.)',
                'D 3 HUDCO, Aurangabad, MH (ESIS Disp.)',
                'D 2 Aurangabad, MH (ESIS Disp.)',
                'D 1 Waluj, Aurangabad, MH (ESIC Disp.)',
                'DCBO - WALUJ'
            ],
            Buldhana: ['DCBO - Khamgaon'],
            Dhule: ['D 1 Dhule, MH (ESIS Disp.)', 'D 2 Dhule, MH (ESIS Disp.)'],
            Jalgaon: [
                'Amalner, Jagaon, MH (ESIS Disp.)',
                'Chalisgaon, Jagaon, MH (ESIS Disp.)',
                'D 2 MIDC, Jalgaon, MH (ESIS Disp.)',
                'D 1 Jalgaon, MH (ESIS Disp.)'
            ],
            Jalna: ['DCBO - Jalna'],
            Kolhapur: ['Ichalkaranji 2, MH (ESIS Disp.)', 'Rajampuri, MH (ESIS Disp.)', 'Tarabai Road, MH (ESIS Disp.)'],
            Nagpur: [
                'Butibori, MH (ESIS Disp.)',
                'Dattatraynagar, Nagpur, MH (ESIS Disp.)',
                'Bagadganj, Nagpur, MH (ESIS Disp.)',
                'Gandhinagar, Nagpur, MH (ESIS Disp.)',
                'Gaddi Godam Chowk, Nagpur, MH (ESIS Disp.)',
                'Kamptee, Nagpur, MH (ESIS Disp.)',
                'Kukade, Nagpur, MH (ESIS Disp.)',
                'Somwari Peth, Nagpur, MH (ESIS Disp.)',
                'Hanumannagar, Nagpur, MH (ESIS Disp.)',
                'Higna Road, Nagpur, MH (ESIS Disp.)',
                'Nandanvan Layout, Nagpur, MH (ESIS Disp.)',
                'Pachpawli, Nagpur, MH (ESIS Disp.)',
                'Mahal, Nagpur, MH (ESIS Disp.)',
                'Ganesh Peth, Nagpur, MH (ESIS Disp.)',
                'Wadi, Nagpur, MH (ESIS Disp.)',
                'Butibori 2, MH (ESIS Disp.)',
                'Kalmeshwar, MH (ESIS Disp.)'
            ],
            Nanded: ['D 1 Nanded, MH (ESIS Disp.)', 'D 2 Nanded, MH (ESIS Disp.)', 'D 3 Nanded, MH (ESIS Disp.)'],
            Nashik: [
                'Ambad, Nasik, MH (ESIS Disp.)',
                'Ashokstumbh, Nasik, MH (ESIS Disp.)',
                'Lekhanagar, CIDCO, MH (ESIS Disp.)',
                'Nasik Road, MH (ESIS Disp.)',
                'Satpur, MH (ESIS Disp.)',
                'DCBO - Sinnar'
            ],
            Mumbai: [
                'Chembur, MH (ESIS Disp.)',
                'Andheri, MH (ESIS Disp.)',
                'Dharavi, MH (ESIS Disp.)',
                'Charkop, Kandivali(W), MH (ESIS Disp.)',
                'Mulund(W), MH (ESIS Disp.)',
                'Parel, MH (ESIS Disp.)',
                'Vile Parle(W), MH (ESIS Disp.)',
                'Worli Central Medical Drug Center, MH (ESIS CMS)',
                'DCBO - Colaba'
            ],
            Pune: [
                'Barshi, MH (ESIS Disp.)',
                'Ichalkaranji, MH (ESIS Disp.)',
                'Nagala Park, Kolhapur, MH (ESIS Disp.)',
                'Tarabai Park, Kolhapur, MH (ESIS Disp.)',
                'Miraj, MH (ESIS Disp.)',
                'Mohannagar, MH (ESIS Disp.)',
                'Chichwad, MH (ESIS Disp.)',
                'Gadital, Hadapsar, MH (ESIS Disp.)',
                'Bhosari, MH (ESIS Disp.)',
                'Rajawada Chowk, Sangli, MH (ESIS Disp.)',
                'Old Civil Hospital, Satara, MH (ESIS Disp.)',
                'Laxmi peth, Solapur, MH (ESIS Disp.)'
            ],
            Raigad: ['DCBO - Panvel'],
            Sangli: ['Kupwad, MH (ESIS Disp.)', 'DCBO - SANGLI'],
            Thane: [
                'Kalyan, MH (ESIS Disp.)',
                'Thane(W), MH (ESIS Disp.)',
                'Ulhasnagar, MH (ESIS Disp.)',
                'Vashi, Navi Mumbai, MH (ESIS Disp.)',
                'Bhiwandi, MH (ESIS Disp.)',
                'DCBO - Murbad'
            ],
            Wardha: ['Haganghat, Nagpur, MH (ESIS Disp.)', 'DCBO - Wardha'],
            Yavatmal: ['DCBO - YAVATMAL']
        }
    },
    mEUD: {
        Karnataka: {
            Chitradurga: ['Chitradurga, KA(ESIS Disp.)', 'Chitradurga, KA(ESIS Disp.2)'],
            'Dakshina Kannada': [
                'Karangalpadi, KA (ESIS Disp)',
                'Kulshekar,  KA (ESIS Disp)',
                "Margan's,  KA (ESIS Disp)",
                'Panambur,  KA (ESIS Disp)',
                'Puttur,  KA (ESIS Disp)'
            ],
            'Uttar Kannada': ['Dandeli,KA(ESIS Disp.)', 'DCBO - Karwar']
        },
        Telangana: {},
        Maharashtra: {}
    }
};
