const States = [
    'Arunachal Pradesh',
    'Assam',
    'Bihar',
    'Chhattisgarh',
    'Goa',
    'Gujarat',
    'Haryana',
    'Himachal Pradesh',
    'Jammu and Kashmir',
    'Jharkhand',
    'Karnataka',
    'Kerala',
    'Madhya Pradesh',
    'Maharashtra',
    'Manipur',
    'Meghalaya',
    'Mizoram',
    'Nagaland',
    'Orissa',
    'Punjab',
    'Rajasthan',
    'Sikkim',
    'Tamil Nadu',
    'Telagana',
    'Tripura',
    'Uttaranchal',
    'Uttar Pradesh',
    'West Bengal',
    'Andaman & Nicobar Islands *',
    'Chandigarh *',
    'Dadra & Nagar Haveli *',
    'Daman & Diu *',
    'Delhi *',
    'Lakshadweep *',
    'Pondicherry *'
];
export default States;
